# BatchNorm1d


[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/docs/learn/layers/02-BatchNorm1d.ipynb)
[![Open in GitHub](https://img.shields.io/badge/Open%20in-GitHub-black?logo=github)](https://github.com/Mitchell-Mirano/sorix/blob/develop/docs/learn/layers/02-BatchNorm1d.ipynb)
[![Open in Docs](https://img.shields.io/badge/Open%20in-Docs-blue?logo=readthedocs)](http://127.0.0.1:8000/sorix/learn/layers/02-BatchNorm1d)


The **BatchNorm1d** layer implements *batch normalization*, a technique designed to stabilize and accelerate the training of deep neural networks by reducing internal covariate shift. This is achieved by normalizing intermediate activations across the batch dimension and subsequently applying a learnable affine transformation.

## Mathematical definition

Let $ \mathbf{X} \in \mathbb{R}^{N \times d} $
be an input tensor representing a batch of $N$ samples, where each sample has $d$ features. Batch normalization operates **feature-wise**, normalizing each feature independently across the batch.

During training, the batch-wise mean and variance are computed as

$$
\boldsymbol{\mu}_B
=
\frac{1}{N}
\sum_{i=1}^{N}
\mathbf{x}_i
\;\in\;
\mathbb{R}^{1 \times d},
$$

$$
\boldsymbol{\sigma}_B^2
=
\frac{1}{N}
\sum_{i=1}^{N}
(\mathbf{x}_i - \boldsymbol{\mu}_B)^2
\;\in\;
\mathbb{R}^{1 \times d},
$$

where $\mathbf{x}_i \in \mathbb{R}^{1 \times d}$ denotes the $i$-th sample in the batch.

## Normalization step

Each input sample is normalized using the batch statistics:

$$
\widehat{\mathbf{X}}
=
\frac{\mathbf{X} - \boldsymbol{\mu}_B}
{\sqrt{\boldsymbol{\sigma}_B^2 + \varepsilon}},
\quad
\widehat{\mathbf{X}} \in \mathbb{R}^{N \times d},
$$

where $\varepsilon > 0$ is a small constant introduced for numerical stability.

## Learnable affine transformation

To preserve the representational capacity of the network, batch normalization introduces two learnable parameters:

- Scale parameter:
  $
  \boldsymbol{\gamma} \in \mathbb{R}^{1 \times d}
  $
- Shift parameter:
  $
  \boldsymbol{\beta} \in \mathbb{R}^{1 \times d}
  $

The final output of the layer is given by

$$
\mathbf{Y}
=
\boldsymbol{\gamma} \odot \widehat{\mathbf{X}}
+
\boldsymbol{\beta},
\quad
\mathbf{Y} \in \mathbb{R}^{N \times d},
$$

where $\odot$ denotes element-wise multiplication applied **column-wise**, i.e., independently to each feature.

## Running statistics and inference mode

In addition to batch statistics, BatchNorm1d maintains *running estimates* of the mean and variance:

$$
\boldsymbol{\mu}_{\text{run}} \in \mathbb{R}^{1 \times d},
\quad
\boldsymbol{\sigma}^2_{\text{run}} \in \mathbb{R}^{1 \times d}.
$$

These statistics are updated during training using an exponential moving average:

$$
\boldsymbol{\mu}_{\text{run}}
\leftarrow
\alpha \boldsymbol{\mu}_{\text{run}}
+
(1 - \alpha)\boldsymbol{\mu}_B,
$$

$$
\boldsymbol{\sigma}^2_{\text{run}}
\leftarrow
\alpha \boldsymbol{\sigma}^2_{\text{run}}
+
(1 - \alpha)\boldsymbol{\sigma}^2_B,
$$

where $\alpha \in (0,1)$ is the momentum parameter controlling the update rate.

During inference (evaluation mode), normalization is performed using these accumulated running statistics instead of the batch statistics, ensuring deterministic behavior:

$$
\widehat{\mathbf{X}}
=
\frac{\mathbf{X} - \boldsymbol{\mu}_{\text{run}}}
{\sqrt{\boldsymbol{\sigma}^2_{\text{run}} + \varepsilon}}.
$$

## Functional view

The BatchNorm1d layer realizes the mapping

$$
\text{BatchNorm1d}:\;
\mathbb{R}^{N \times d}
\;\longrightarrow\;
\mathbb{R}^{N \times d},
$$

where normalization and affine reparameterization are applied independently to each feature across the batch.

## Parameterization and gradients

The learnable parameters $\boldsymbol{\gamma}$ and $\boldsymbol{\beta}$ are represented as `tensor` objects with `requires_grad=True`. Gradients are computed with respect to these parameters, as well as with respect to the input tensor $\mathbf{X}$, during backpropagation:

$$
\frac{\partial \mathcal{L}}{\partial \boldsymbol{\gamma}}, \quad
\frac{\partial \mathcal{L}}{\partial \boldsymbol{\beta}}, \quad
\frac{\partial \mathcal{L}}{\partial \mathbf{X}}.
$$

The running statistics are treated as buffers and do not participate in gradient computation.

## Multi-device support

BatchNorm1d is device-aware and supports execution on CPU and GPU backends. Learnable parameters are stored as tensors on the selected device, while running statistics are maintained as NumPy or CuPy arrays and transferred consistently when changing devices via the `to(device)` method.

## Parameter interface

The trainable parameters of the layer are exposed through the `parameters()` method, which returns

$$
\{\boldsymbol{\gamma}, \boldsymbol{\beta}\}.
$$

## Statistical interpretation

From a statistical perspective, BatchNorm1d performs a feature-wise standardization of the input distribution, followed by a learned affine transformation. This can be interpreted as dynamically re-centering and re-scaling the feature space, which improves numerical conditioning and facilitates optimization in deep networks.


In [1]:
# Uncomment the next line and run this cell to install sorix
#!pip install 'sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop'

In [2]:
from sorix import tensor
from sorix.nn import BatchNorm1d
import numpy as np

In [3]:
# number of samples and features
samples = 8
features = 3

# input tensor X ∈ ℝ^(samples × features)
X = tensor(np.random.randn(samples, features))
X


tensor([[-0.35322232,  1.58062812, -2.27080676],
        [-1.370734  ,  0.82210836,  0.57517109],
        [ 0.87794241, -0.20541586,  0.05401262],
        [ 0.52735877,  0.18637851, -1.25259922],
        [-1.87028732,  0.939324  , -0.87727431],
        [ 0.11896393,  0.57087096,  0.59203335],
        [ 1.56081025, -0.13111647,  0.30010904],
        [ 0.8176216 , -0.7060233 , -1.56098952]], dtype=sorix.float64)

In [4]:
bn = BatchNorm1d(features)

# γ ∈ ℝ^(1 × features), β ∈ ℝ^(1 × features)
print(bn.gamma)
print(bn.beta)


tensor([[1., 1., 1.]], requires_grad=True)
tensor([[0., 0., 0.]], requires_grad=True)


In [5]:
# forward pass (training mode)
Y = bn(X)
Y


tensor([[-0.35657707,  1.73737614, -1.69042069],
        [-1.28266386,  0.6378376 ,  1.11351995],
        [ 0.76396572, -0.85164564,  0.60005938],
        [ 0.44488252, -0.28370657, -0.68725283],
        [-1.73733159,  0.80775158, -0.31747175],
        [ 0.07318255,  0.27364775,  1.13013314],
        [ 1.38547689, -0.7439424 ,  0.84252077],
        [ 0.70906482, -1.57731846, -0.99108797]], dtype=sorix.float64, requires_grad=True)

In [6]:
# running statistics after the forward pass
print(bn.running_mean)
print(bn.running_var)


tensor([[ 0.00385567,  0.03820943, -0.0555043 ]], dtype=sorix.float64)
tensor([[1.02071792, 0.94758867, 1.00301989]], dtype=sorix.float64)


In [7]:
# inference mode
bn.training = False
Y_eval = bn(X)
Y_eval


tensor([[-0.35343379,  1.58449203, -2.21195401],
        [-1.36056119,  0.80528174,  0.62972211],
        [ 0.86516619, -0.25027078,  0.10935138],
        [ 0.51816045,  0.15221077, -1.1952855 ],
        [-1.85501627,  0.92569473, -0.8205279 ],
        [ 0.11393351,  0.54719121,  0.64655889],
        [ 1.54106496, -0.17394469,  0.35507582],
        [ 0.80546098, -0.76453355, -1.50320966]], dtype=sorix.float64, requires_grad=True)