# BatchNorm1d


[!["Open In Colab"](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/docs/learn/layers/02-BatchNorm1d.ipynb)
[!["Open in GitHub"](https://img.shields.io/badge/Open%20in-GitHub-black?logo=github)](https://github.com/Mitchell-Mirano/sorix/blob/develop/docs/learn/layers/02-BatchNorm1d.ipynb)
[!["Open in Docs"](https://img.shields.io/badge/Open%20in-Docs-blue?logo=readthedocs)](http://127.0.0.1:8000/sorix/learn/layers/02-BatchNorm1d)


The **BatchNorm1d** layer implements *batch normalization*, a technique designed to stabilize and accelerate the training of deep neural networks by reducing internal covariate shift. This is achieved by normalizing intermediate activations across the batch dimension and subsequently applying a learnable affine transformation.

## Mathematical definition

Let $ \mathbf{X} \in \mathbb{R}^{N \times d} $
be an input tensor representing a batch of $N$ samples, where each sample has $d$ features. Batch normalization operates **feature-wise**, normalizing each feature independently across the batch.

During training, the batch-wise mean and variance are computed as

$$
\boldsymbol{\mu}_B
=
\frac{1}{N}
\sum_{i=1}^{N}
\mathbf{x}_i
\;\in\;
\mathbb{R}^{1 \times d},
$$

$$
\boldsymbol{\sigma}_B^2
=
\frac{1}{N}
\sum_{i=1}^{N}
(\mathbf{x}_i - \boldsymbol{\mu}_B)^2
\;\in\;
\mathbb{R}^{1 \times d},
$$

where $\mathbf{x}_i \in \mathbb{R}^{1 \times d}$ denotes the $i$-th sample in the batch.

## Normalization step

Each input sample is normalized using the batch statistics:

$$
\widehat{\mathbf{X}}
=
\frac{\mathbf{X} - \boldsymbol{\mu}_B}
{\sqrt{\boldsymbol{\sigma}_B^2 + \varepsilon}},
\quad
\widehat{\mathbf{X}} \in \mathbb{R}^{N \times d},
$$

where $\varepsilon > 0$ is a small constant introduced for numerical stability.

## Learnable affine transformation

To preserve the representational capacity of the network, batch normalization introduces two learnable parameters:

- Scale parameter:
  $
  \boldsymbol{\gamma} \in \mathbb{R}^{1 \times d}
  $
- Shift parameter:
  $
  \boldsymbol{\beta} \in \mathbb{R}^{1 \times d}
  $

The final output of the layer is given by

$$
\mathbf{Y}
=
\boldsymbol{\gamma} \odot \widehat{\mathbf{X}}
+
\boldsymbol{\beta},
\quad
\mathbf{Y} \in \mathbb{R}^{N \times d},
$$

where $\odot$ denotes element-wise multiplication applied **column-wise**, i.e., independently to each feature.

## Running statistics and inference mode

In addition to batch statistics, BatchNorm1d maintains *running estimates* of the mean and variance:

$$
\boldsymbol{\mu}_{\text{run}} \in \mathbb{R}^{1 \times d},
\quad
\boldsymbol{\sigma}^2_{\text{run}} \in \mathbb{R}^{1 \times d}.
$$

These statistics are updated during training using an exponential moving average:

$$
\boldsymbol{\mu}_{\text{run}}
\leftarrow
(1 - \alpha) \boldsymbol{\mu}_{\text{run}}
+
\alpha \boldsymbol{\mu}_B,
$$

$$
\boldsymbol{\sigma}^2_{\text{run}}
\leftarrow
(1 - \alpha) \boldsymbol{\sigma}^2_{\text{run}}
+
\alpha \boldsymbol{\sigma}^2_B,
$$

where $\alpha$ is the momentum parameter. During inference (evaluation mode), normalization is performed using these constant running statistics:

$$
\widehat{\mathbf{X}}
=
\frac{\mathbf{X} - \boldsymbol{\mu}_{\text{run}}}
{\sqrt{\boldsymbol{\sigma}^2_{\text{run}} + \varepsilon}}.
$$

## Functional view

The BatchNorm1d layer realizes the mapping

$$
\text{BatchNorm1d}:\;
\mathbb{R}^{N \times d}
\;\longrightarrow\;
\mathbb{R}^{N \times d},
$$

where normalization and affine reparameterization are applied independently to each feature across the batch.

## Backward Pass and Gradient Computation

Computing the gradient $\frac{\partial \mathcal{L}}{\partial \mathbf{X}}$ in BatchNorm is more involved than in direct activations because every $\mathbf{x}_i$ contributes to the batch statistics ($\boldsymbol{\mu}_B$ and $\boldsymbol{\sigma}_B^2$), which in turn affect **all** normalized outputs $\widehat{\mathbf{X}}$ in the batch.

Applying the **Complete Chain Rule**, the gradient with respect to a single sample $\mathbf{x}_i$ is the sum of three computational paths:

$$\frac{\partial \mathcal{L}}{\partial \mathbf{x}_i} = \underbrace{\frac{\partial \mathcal{L}}{\partial \widehat{\mathbf{x}}_i} \frac{\partial \widehat{\mathbf{x}}_i}{\partial \mathbf{x}_i}}_{\text{Direct path}} + \underbrace{\left( \sum_{j=1}^N \frac{\partial \mathcal{L}}{\partial \widehat{\mathbf{x}}_j} \frac{\partial \widehat{\mathbf{x}}_j}{\partial \boldsymbol{\mu}_B} \right) \frac{\partial \boldsymbol{\mu}_B}{\partial \mathbf{x}_i}}_{\text{Path via Mean}} + \underbrace{\left( \sum_{j=1}^N \frac{\partial \mathcal{L}}{\partial \widehat{\mathbf{x}}_j} \frac{\partial \widehat{\mathbf{x}}_j}{\partial \boldsymbol{\sigma}_B^2} \right) \frac{\partial \boldsymbol{\sigma}_B^2}{\partial \mathbf{x}_i}}_{\text{Path via Variance}}$$

### Step-by-Step Components:

1. **Derivative w.r.t Normalized Activation**: From $\mathbf{y}_i = \boldsymbol{\gamma} \widehat{\mathbf{x}}_i + \boldsymbol{\beta}$, we have $\nabla_{\widehat{\mathbf{x}}_i} \mathcal{L} = \nabla_{\mathbf{y}_i} \mathcal{L} \odot \boldsymbol{\gamma}$.
2. **The Variance path**: Since $\boldsymbol{\sigma}_B^2 = \frac{1}{N} \sum (\mathbf{x}_j - \boldsymbol{\mu}_B)^2$, its contribution accounts for how the spread of the batch affects the scaling of every sample.
3. **The Mean path**: Since $\boldsymbol{\mu}_B = \frac{1}{N} \sum \mathbf{x}_j$, its contribution accounts for how shifting the batch center affects every centered sample $(\mathbf{x}_j - \boldsymbol{\mu}_B)$.

By substituting the partial derivatives ($\frac{\partial \boldsymbol{\mu}_B}{\partial \mathbf{x}_i} = \frac{1}{N}$ and $\frac{\partial \boldsymbol{\sigma}_B^2}{\partial \mathbf{x}_i} = \frac{2(\mathbf{x}_i - \boldsymbol{\mu}_B)}{N}$), we obtain the consolidated analytical result used in the backpropagation engine:

$$\frac{\partial \mathcal{L}}{\partial \mathbf{x}_i} = \frac{\boldsymbol{\gamma}}{N \sqrt{\boldsymbol{\sigma}_B^2 + \varepsilon}} \left[ N \nabla_{\mathbf{y}_i} \mathcal{L} - \sum_{j=1}^N \nabla_{\mathbf{y}_j} \mathcal{L} - \widehat{\mathbf{x}}_i \sum_{j=1}^N \left( \nabla_{\mathbf{y}_j} \mathcal{L} \odot \widehat{\mathbf{x}}_j \right) \right]$$

This formulation captures the "batch-talk" inherently required by the normalization process.

## Multi-device support

BatchNorm1d is device-aware and supports execution on CPU and GPU backends. Learnable parameters are stored as tensors on the selected device, while running statistics are maintained as NumPy or CuPy arrays.

## Parameter interface

The trainable parameters of the layer are exposed through the `parameters()` method, which returns

$$
\{\boldsymbol{\gamma}, \boldsymbol{\beta}\}.
$$


In [1]:
# Uncomment to install sorix
#!pip install 'sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop'

In [2]:
from sorix import tensor
from sorix.nn import BatchNorm1d
import numpy as np

In [3]:
samples, features = 8, 3
X = tensor(np.random.randn(samples, features))
X

tensor([[ 2.40472266, -0.77822457,  0.07919048],
        [ 1.49351479, -1.2995823 , -0.34300973],
        [-0.14683536, -1.40834977,  0.73702532],
        [-0.18998278,  0.19788315,  1.66891079],
        [-1.57381531,  0.11291339,  0.78227442],
        [ 1.05667179,  0.81013338,  1.52372511],
        [-0.29665275, -0.55715534,  0.39900719],
        [-1.01441622, -2.07368872, -1.13408794]], dtype=sorix.float64)

In [4]:
bn = BatchNorm1d(features)
print(bn.gamma)
print(bn.beta)

tensor([[1., 1., 1.]], requires_grad=True)
tensor([[0., 0., 0.]], requires_grad=True)


In [5]:
Y = bn(X)
Y

tensor([[ 1.75707625, -0.17083722, -0.4405348 ],
        [ 1.0253536 , -0.75026593, -0.92371239],
        [-0.2918885 , -0.87114837,  0.31230957],
        [-0.32653695,  0.91399342,  1.37878506],
        [-1.43778899,  0.81955938,  0.36409389],
        [ 0.67455777,  1.59443862,  1.21263056],
        [-0.4121956 ,  0.07485563, -0.07452772],
        [-0.98857757, -1.61059553, -1.82904417]], dtype=sorix.float64, requires_grad=True)

In [6]:
print(bn.running_mean)
print(bn.running_var)

tensor([[ 0.02166509, -0.06245088,  0.04641295]], dtype=sorix.float64)
tensor([[1.07722746, 0.99252478, 0.98725885]], dtype=sorix.float64)


In [7]:
bn.training = False
Y_eval = bn(X)
Y_eval

tensor([[ 2.29603663, -0.71846044,  0.0329882 ],
        [ 1.41810289, -1.24177516, -0.3919255 ],
        [-0.1623474 , -1.3509509 ,  0.69505095],
        [-0.20391922,  0.26131123,  1.63292565],
        [-1.53721902,  0.17602253,  0.74059086],
        [ 0.99721187,  0.87585963,  1.48680686],
        [-0.30669398, -0.49656139,  0.35486037],
        [-0.99824723, -2.01878729, -1.18808798]], dtype=sorix.float64, requires_grad=True)