# Tensor

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/examples/basics/1-tensor.ipynb)


## Install Sorix

In [1]:
!pip install sorix

zsh:1: command not found: pip


In [2]:
import sorix
import numpy as np
import pandas as pd

## Create a Tensor

In [3]:
# from list
a = sorix.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [4]:
a.shape

(3,)

In [5]:
len(a)

3

In [6]:
#from numpy
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.92834196 0.40216768 0.58367303 0.62642475 0.86454841]
 [0.46351291 0.26748831 0.28685313 0.41542565 0.37860275]
 [0.68697752 0.51067524 0.41068683 0.70232872 0.26160215]
 [0.02551269 0.37353917 0.86671375 0.52342072 0.9328537 ]
 [0.91198808 0.14917277 0.53125841 0.49215737 0.22369584]], shape=(5, 5), device=cpu, requires_grad=False)

In [7]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

In [8]:
# using sorix

In [9]:
t = sorix.as_tensor([1,2,3])
t

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [10]:
t = sorix.randn(3,4)
t

Tensor(
[[-1.0066249   0.24906394  1.17425098 -0.47437147]
 [-0.75192468  0.24541542 -1.07033162  2.04086756]
 [-0.27952912  1.53565357  0.20688112 -0.00545166]], shape=(3, 4), device=cpu, requires_grad=False)

In [11]:
t = sorix.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), device=cpu, requires_grad=False)

In [12]:
t = sorix.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), device=cpu, requires_grad=False)

In [13]:
t = sorix.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), device=cpu, requires_grad=False)

In [14]:
t = sorix.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), device=cpu, requires_grad=False)

In [15]:
t = sorix.randint(0,10,(3,4))
t

Tensor(
[[0 4 1 2]
 [1 3 0 1]
 [6 0 6 2]], shape=(3, 4), device=cpu, requires_grad=False)

In [16]:
t = sorix.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), device=cpu, requires_grad=False)

In [17]:
t = sorix.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), device=cpu, requires_grad=False)

In [18]:
t = sorix.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [19]:
t = sorix.randperm(5)
t

Tensor(
[3 1 2 4 0], shape=(5,), device=cpu, requires_grad=False)

## Basic Operations

In [20]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [21]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [22]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [23]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [24]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [25]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

## Spliting

In [26]:
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.12269919 0.18222564 0.27339509 0.7825955  0.03809932]
 [0.28668049 0.43097469 0.41776273 0.93710241 0.12471315]
 [0.48594462 0.72277305 0.11965256 0.45409257 0.61237676]
 [0.50705189 0.09164688 0.99716678 0.8498959  0.1608676 ]
 [0.37874334 0.92062032 0.25731104 0.82792985 0.90583267]], shape=(5, 5), device=cpu, requires_grad=False)

In [27]:
a[3,:]

Tensor(
[0.50705189 0.09164688 0.99716678 0.8498959  0.1608676 ], shape=(5,), device=cpu, requires_grad=False)

In [28]:
a[3,3]

Tensor(
0.8498959010908615, shape=(), device=cpu, requires_grad=False)

In [29]:
a[:,3]

Tensor(
[0.7825955  0.93710241 0.45409257 0.8498959  0.82792985], shape=(5,), device=cpu, requires_grad=False)

## Auto Grad

In [30]:
a = sorix.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [31]:
b =sorix.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [32]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
[Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)]
grad(a) [0 0 0]
grad(b) [0 0 0]


In [33]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [34]:
with sorix.no_grad():
    a = sorix.tensor([1,2,3], requires_grad=True)
    b = sorix.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

[]

## Using GPU

In [35]:
device = 'gpu' if sorix.cuda.is_available() else 'cpu'
device

❌ CuPy is not installed.


'cpu'

In [36]:
a = sorix.tensor(np.random.rand(5,5), device=device)
b = sorix.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.85809798 1.6420937  1.93144713 0.8534766  0.66186246]
 [1.04339068 1.35313717 1.01722601 1.01029632 0.6303016 ]
 [0.40420829 1.57396382 0.85243554 0.98129645 0.62872305]
 [0.89235805 1.10502466 1.12475301 1.36773501 1.44891351]
 [1.4967001  1.07280851 1.54628203 0.80325728 0.75952818]], shape=(5, 5), device=cpu, requires_grad=False)
[]
cpu


In [37]:
a = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.18830809 1.17985329 1.27350604 0.84894476 0.53931726]
 [1.08427751 1.60454623 1.07288026 0.83750141 0.64572027]
 [1.46097756 1.11097081 1.30806595 1.71552826 1.67276802]
 [1.08395256 1.07861933 0.15551077 1.42442545 0.70606453]
 [1.87296262 1.70648333 1.0841833  0.26920985 0.49804396]], shape=(5, 5), device=cpu, requires_grad=True)
[Tensor(
[[0.9995799  0.76251821 0.74970986 0.29318487 0.07707955]
 [0.73043784 0.67169215 0.49435716 0.16822957 0.31566743]
 [0.89234809 0.58747323 0.40076855 0.87520076 0.97586257]
 [0.79106063 0.09117108 0.021465   0.46813181 0.55584256]
 [0.93204424 0.89378769 0.69044682 0.0853871  0.15176247]], shape=(5, 5), device=cpu, requires_grad=True), Tensor(
[[0.18872819 0.41733509 0.52379619 0.55575989 0.46223771]
 [0.35383967 0.93285407 0.57852309 0.66927183 0.33005284]
 [0.56862947 0.52349758 0.9072974  0.8403275  0.69690545]
 [0.29289193 0.98744825 0.13404577 0.95629363 0.15022198]
 [0.94091838 0.81269564 0.39373648 0.18382275 0.34628149]], shape=