# Tensor
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/docs/learn/01-tensor.ipynb)
[![Open in GitHub](https://img.shields.io/badge/Open%20in-GitHub-black?logo=github)](https://github.com/Mitchell-Mirano/sorix/blob/develop/docs/learn/01-tensor.ipynb)
[![Open in Docs](https://img.shields.io/badge/Open%20in-Docs-blue?logo=readthedocs)](http://127.0.0.1:8000/learn/01-tensor/)


The **Tensor** is Sorix's core data structure, analogous to **NumPy** arrays but with the added ability to record every operation within a [computational graph](../02-graph). This operation tracking is what enables the automatic computation of gradients[(Autograd)](../03-autograd).

In [6]:
# Uncomment the next line and run this cell to install sorix
#!pip install 'sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop'

In [6]:
import sorix
import numpy as np
import pandas as pd

## Create a Tensor
A tensor can be initialized from a NumPy array, a pandas DataFrame, or a Python list. Internally, Sorix converts any supported input into a NumPy array.

In [7]:
# from list
a = sorix.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [8]:
#from numpy
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.26103914 0.82704748 0.31740097 0.18041764 0.89844797]
 [0.60343146 0.33064018 0.55333563 0.01919862 0.17008929]
 [0.21479971 0.48801356 0.06972932 0.43100927 0.9317665 ]
 [0.90065646 0.88185773 0.69416948 0.73985093 0.67909367]
 [0.31243475 0.868807   0.72736226 0.49375667 0.51436013]], shape=(5, 5), device=cpu, requires_grad=False)

In [9]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

To access the underlying NumPy array within a Sorix tensor, you can use the `data` attribute and apply any NumPy operation directly to it.

In [10]:
t.data

array([[0.464307, 0.278199, 0.793136, 0.618634, 0.729128],
       [0.182403, 0.187902, 0.957675, 0.784397, 0.467162],
       [0.664873, 0.887387, 0.035765, 0.841349, 0.687347],
       [0.906638, 0.473387, 0.639977, 0.352944, 0.432614],
       [0.725385, 0.90451 , 0.622032, 0.783273, 0.980809]])

In [34]:
type(t.data)

numpy.ndarray

## Sorix utils to create tensors

In [11]:
t = sorix.as_tensor([1,2,3])
t

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [12]:
t = sorix.randn(3,4)
t

Tensor(
[[ 1.9094233   1.87395467 -0.74233853  1.2301894 ]
 [ 1.00624556 -0.39046544 -1.2465176   1.17108726]
 [-0.58068142 -0.19076851  1.62583008  0.05123753]], shape=(3, 4), device=cpu, requires_grad=False)

In [13]:
t = sorix.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), device=cpu, requires_grad=False)

In [14]:
t = sorix.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), device=cpu, requires_grad=False)

In [15]:
t = sorix.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), device=cpu, requires_grad=False)

In [16]:
t = sorix.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), device=cpu, requires_grad=False)

In [17]:
t = sorix.randint(0,10,(3,4))
t

Tensor(
[[4 4 1 4]
 [0 6 5 8]
 [6 2 7 3]], shape=(3, 4), device=cpu, requires_grad=False)

In [18]:
t = sorix.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), device=cpu, requires_grad=False)

In [19]:
t = sorix.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), device=cpu, requires_grad=False)

In [20]:
t = sorix.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [21]:
t = sorix.randperm(5)
t

Tensor(
[2 4 0 1 3], shape=(5,), device=cpu, requires_grad=False)

## Basic Operations

In [22]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [23]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [24]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [25]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [26]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [27]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

## Slicing

In [28]:
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.533261   0.54580051 0.81966961 0.16125006 0.19406496]
 [0.92803021 0.14010897 0.90195723 0.62335444 0.27689092]
 [0.00376482 0.27292441 0.234567   0.46286437 0.37391756]
 [0.22265504 0.93628789 0.11980395 0.47618568 0.81324681]
 [0.73690523 0.3150144  0.53104157 0.53582248 0.53764228]], shape=(5, 5), device=cpu, requires_grad=False)

In [29]:
a[3,:]

Tensor(
[0.22265504 0.93628789 0.11980395 0.47618568 0.81324681], shape=(5,), device=cpu, requires_grad=False)

In [30]:
a[3,3]

Tensor(
0.47618568372171655, shape=(), device=cpu, requires_grad=False)

In [35]:
a[:,3]

Tensor(
[0.00970981 0.45828279 0.16871779 0.93106908 0.71455981], shape=(5,), device=gpu, requires_grad=False)

## Using GPU

When running on a GPU, Sorix uses **CuPy** arrays instead of NumPy. You can enable GPU execution by setting the `device` parameter to `'gpu'` (the default is `'cpu'`). When `'gpu'` is specified, Sorix creates CuPy-based tensors and executes all operations on the GPU.

To check whether a GPU is available, you can call `sorix.cuda.is_available()`. Refer to the examples below.


In [32]:
device = 'gpu' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [33]:
a = sorix.tensor(np.random.rand(5,5), device=device)
b = sorix.tensor(np.random.rand(5,5), device=device)
c = a + b
c

Tensor(
[[1.28204074 1.52585648 1.68812989 0.2422148  1.06811271]
 [0.93670912 1.47988872 0.76452445 1.30172208 0.60486268]
 [0.90259124 1.91283999 0.38445446 1.0423669  0.58394127]
 [0.82604729 0.91417964 0.66966319 1.49362473 1.4598561 ]
 [1.39870376 0.70303495 0.84490695 1.36847297 1.04001228]], shape=(5, 5), device=gpu, requires_grad=False)