# Tensor
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/docs/learn/01-tensor.ipynb)
[![Open in GitHub](https://img.shields.io/badge/Open%20in-GitHub-black?logo=github)](https://github.com/Mitchell-Mirano/sorix/blob/develop/docs/learn/01-tensor.ipynb)
[![Open in Docs](https://img.shields.io/badge/Open%20in-Docs-blue?logo=readthedocs)](http://127.0.0.1:8000/learn/01-tensor/)


The **Tensor** is Sorix's core data structure, analogous to **NumPy** arrays but with the added ability to record every operation within a [computational graph](../02-graph). This operation tracking is what enables the automatic computation of gradients[(Autograd)](../03-autograd).

In [6]:
# Uncomment the next line and run this cell to install sorix
#!pip install 'sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop'

In [1]:
import sorix
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Create a Tensor
A tensor can be initialized from a NumPy array, a pandas DataFrame, or a Python list. Internally, Sorix converts any supported input into a NumPy array.

In [5]:
# from list
a = sorix.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), dtype=int64, device=cpu, requires_grad=False)

In [4]:
#from numpy
a = sorix.tensor(np.random.rand(5,5),dtype=sorix.float32)
a

Tensor(
[[0.01223465 0.85945845 0.5093941  0.600978   0.2989264 ]
 [0.22684598 0.06075108 0.803564   0.66998327 0.957295  ]
 [0.60993266 0.9914627  0.50465184 0.511373   0.43485722]
 [0.24191551 0.84083015 0.4452216  0.36084554 0.53567845]
 [0.2647182  0.1793769  0.5946919  0.56668794 0.8740835 ]], shape=(5, 5), dtype=float32, device=cpu, requires_grad=False)

In [5]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), dtype=float64, device=cpu, requires_grad=False)

To access the underlying NumPy array within a Sorix tensor, you can use the `data` attribute and apply any NumPy operation directly to it.

In [6]:
t.data

array([[0.464307, 0.278199, 0.793136, 0.618634, 0.729128],
       [0.182403, 0.187902, 0.957675, 0.784397, 0.467162],
       [0.664873, 0.887387, 0.035765, 0.841349, 0.687347],
       [0.906638, 0.473387, 0.639977, 0.352944, 0.432614],
       [0.725385, 0.90451 , 0.622032, 0.783273, 0.980809]])

In [7]:
type(t.data)

numpy.ndarray

## Sorix utils to create tensors

In [8]:
t = sorix.as_tensor([1,2,3])
t

Tensor(
[1 2 3], shape=(3,), dtype=int64, device=cpu, requires_grad=False)

In [9]:
t = sorix.randn(3,4)
t

Tensor(
[[-0.50572497  0.40243877  1.8802033   0.02208722]
 [ 2.1586447  -0.05848246 -1.42692419  0.90255644]
 [ 0.26617453  0.96622245 -0.19176217 -0.51926245]], shape=(3, 4), dtype=float64, device=cpu, requires_grad=False)

In [10]:
t = sorix.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float64, device=cpu, requires_grad=False)

In [11]:
t = sorix.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float64, device=cpu, requires_grad=False)

In [12]:
t = sorix.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float64, device=cpu, requires_grad=False)

In [13]:
t = sorix.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), dtype=int64, device=cpu, requires_grad=False)

In [14]:
t = sorix.randint(0,10,(3,4))
t

Tensor(
[[5 6 0 1]
 [0 5 9 7]
 [2 0 0 5]], shape=(3, 4), dtype=int64, device=cpu, requires_grad=False)

In [15]:
t = sorix.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64, device=cpu, requires_grad=False)

In [16]:
t = sorix.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), dtype=float64, device=cpu, requires_grad=False)

In [20]:
t = sorix.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [17]:
t = sorix.randperm(5)
t

Tensor(
[4 1 0 3 2], shape=(5,), dtype=int64, device=cpu, requires_grad=False)

## Basic Operations

In [18]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), dtype=int64, device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), dtype=int64, device=cpu, requires_grad=False)


In [19]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), dtype=int64, device=cpu, requires_grad=False)

In [20]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), dtype=int64, device=cpu, requires_grad=False)

In [21]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), dtype=int64, device=cpu, requires_grad=False)

In [22]:
c = a@b
c

Tensor(
26, shape=(), dtype=int64, device=cpu, requires_grad=False)

In [23]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), dtype=int64, device=cpu, requires_grad=False)

## Slicing

In [24]:
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.09655126 0.48785437 0.83569654 0.19210977 0.92475581]
 [0.88375166 0.81737258 0.01034406 0.09525237 0.10220104]
 [0.30356184 0.92937694 0.73074351 0.06734836 0.91147181]
 [0.38890441 0.9186451  0.65997484 0.4150158  0.30729607]
 [0.52981299 0.91175568 0.80436941 0.30989116 0.98748438]], shape=(5, 5), dtype=float64, device=cpu, requires_grad=False)

In [25]:
a[3,:]

Tensor(
[0.38890441 0.9186451  0.65997484 0.4150158  0.30729607], shape=(5,), dtype=float64, device=cpu, requires_grad=False)

In [26]:
a[3,3]

Tensor(
0.41501580453064746, shape=(), dtype=float64, device=cpu, requires_grad=False)

In [27]:
a[:,3]

Tensor(
[0.19210977 0.09525237 0.06734836 0.4150158  0.30989116], shape=(5,), dtype=float64, device=cpu, requires_grad=False)

## Using GPU

When running on a GPU, Sorix uses **CuPy** arrays instead of NumPy. You can enable GPU execution by setting the `device` parameter to `'cuda'` (the default is `'cpu'`). When `'cuda'` is specified, Sorix creates CuPy-based tensors and executes all operations on the GPU.

To check whether a GPU is available, you can call `sorix.cuda.is_available()`. Refer to the examples below.


In [30]:
device = 'cuda' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 14.0.1


'cuda'

In [31]:
a = sorix.tensor(np.random.rand(5,5), device=device)
b = sorix.tensor(np.random.rand(5,5), device=device)
c = a + b
c

Tensor(
[[0.93229431 0.82418341 0.25150406 1.33612475 1.33626272]
 [0.7756705  0.82444902 1.1067692  1.13306929 1.52924763]
 [1.72117972 1.76722034 0.40925584 0.41622543 0.86008552]
 [0.40787171 1.39576969 1.2267005  0.89335616 0.8639851 ]
 [1.11311537 0.96656105 1.68000239 0.9586354  1.26361418]], shape=(5, 5), dtype=float64, device=gpu, requires_grad=False)