# Layers
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/docs/learn/layers.ipynb)

## Install Sorix

In [1]:
!pip install sorix

zsh:1: command not found: pip


## Import Sorix

In [2]:
import numpy as np
from sorix import tensor
from sorix.nn import Relu,Linear,BatchNorm1D
import sorix

## Random Dataset

In [3]:
features = 5
classes = 2
examples = 10

In [4]:
# create random data
X = tensor(np.random.randn(examples, features))
X

Tensor(
[[-1.4326771  -0.00919046 -0.14949294 -0.95466182 -0.81103085]
 [-0.90918112 -2.01715476  1.14501517 -0.71773688  1.47703582]
 [-1.51712344  0.28947914  0.4378121  -0.26421133 -1.63067278]
 [ 0.92393616  0.53607195 -0.11341251  0.87042314  0.73970899]
 [ 2.6137361   0.17933893 -0.69928271 -1.2849901   0.38968263]
 [ 1.67343352 -0.84421506  1.46524357 -0.570808    0.13940441]
 [-2.60760511 -0.54087023 -0.27773379  2.08071396  0.57881134]
 [-2.79298068 -0.21056222  0.05317133  0.2136953   0.71217294]
 [-0.80248609  0.31530067 -1.16611483 -1.74417722 -0.9131638 ]
 [-2.21407647  1.09934984  1.78074141 -0.4218447   1.86345637]], shape=(10, 5), device=cpu, requires_grad=False)

## Linear

In [5]:
linear = Linear(features,classes)
linear.W,linear.b

(Tensor(
 [[-0.25189701 -0.70765587]
  [-0.35987971 -0.15308859]
  [-0.75610893  0.11274867]
  [ 0.03564675 -0.02640338]
  [-0.54468212 -0.47375451]], shape=(5, 2), device=cpu, requires_grad=True),
 Tensor(
 [[0. 0.]], shape=(1, 2), device=cpu, requires_grad=True))

In [6]:
linear(X)

Tensor(
[[ 0.88495089  1.40783001]
 [-0.74090311  0.40048797]
 [ 0.82572758  1.85816275]
 [-0.71178446 -1.12210504]
 [-0.45225772 -2.10660946]
 [-1.32187931 -0.9407433 ]
 [ 0.82039564  1.56762164]
 [ 0.3588269   1.67166142]
 [ 1.40559312  0.8668048 ]
 [-2.2143777   0.72759978]], shape=(10, 2), device=cpu, requires_grad=True)

## Batch Norm

In [7]:
bn = BatchNorm1D(classes)
bn.gamma,bn.beta

(Tensor(
 [[1. 1.]], shape=(1, 2), device=cpu, requires_grad=True),
 Tensor(
 [[0. 0.]], shape=(1, 2), device=cpu, requires_grad=True))

In [8]:
bn(linear(X))

Tensor(
[[ 0.91158988  0.75127628]
 [-0.57123139 -0.02511277]
 [ 0.85757667  1.09836137]
 [-0.54467443 -1.19862137]
 [-0.30797927 -1.95740878]
 [-1.10109685 -1.05884038]
 [ 0.8527138   0.87443254]
 [ 0.43175107  0.95461915]
 [ 1.38642917  0.33429175]
 [-1.91507866  0.22700222]], shape=(10, 2), device=cpu, requires_grad=True)

## ReLU

In [9]:
relu = Relu()
relu(X)

Tensor(
[[0.         0.         0.         0.         0.        ]
 [0.         0.         1.14501517 0.         1.47703582]
 [0.         0.28947914 0.4378121  0.         0.        ]
 [0.92393616 0.53607195 0.         0.87042314 0.73970899]
 [2.6137361  0.17933893 0.         0.         0.38968263]
 [1.67343352 0.         1.46524357 0.         0.13940441]
 [0.         0.         0.         2.08071396 0.57881134]
 [0.         0.         0.05317133 0.2136953  0.71217294]
 [0.         0.31530067 0.         0.         0.        ]
 [0.         1.09934984 1.78074141 0.         1.86345637]], shape=(10, 5), device=cpu, requires_grad=False)

## Linear + ReLU

In [10]:
relu(linear(X))

Tensor(
[[0.88495089 1.40783001]
 [0.         0.40048797]
 [0.82572758 1.85816275]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.82039564 1.56762164]
 [0.3588269  1.67166142]
 [1.40559312 0.8668048 ]
 [0.         0.72759978]], shape=(10, 2), device=cpu, requires_grad=True)

## Linear + BatchNorm + ReLU

In [11]:
relu(bn(linear(X)))

Tensor(
[[0.91158988 0.75127628]
 [0.         0.        ]
 [0.85757667 1.09836137]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.8527138  0.87443254]
 [0.43175107 0.95461915]
 [1.38642917 0.33429175]
 [0.         0.22700222]], shape=(10, 2), device=cpu, requires_grad=True)

## Without bias

In [12]:
linear = Linear(features,classes,bias=False)
relu(bn(linear(X)))

Tensor(
[[0.28462444 0.        ]
 [0.38979743 1.06676039]
 [0.         0.        ]
 [0.         0.30066459]
 [1.55899067 0.        ]
 [0.71279682 0.        ]
 [0.         0.36134105]
 [0.         0.54201467]
 [0.98830535 0.        ]
 [0.         1.88287324]], shape=(10, 2), device=cpu, requires_grad=True)

## Using GPU

In [13]:
device = 'gpu' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

## Linear + GPU

In [14]:
features = 5
classes = 2
examples = 10

X = tensor(np.random.randn(examples, features), device=device)
linear = Linear(features,classes).to(device)
linear(X)

Tensor(
[[ 0.04409816 -1.81807428]
 [ 2.04750706  2.80972806]
 [-0.33237191  1.1430097 ]
 [ 0.76156729 -1.62339694]
 [-0.20745892  0.49827288]
 [-0.1306569   1.17736757]
 [-0.16330679 -0.15796541]
 [ 0.09257982 -1.8448066 ]
 [ 0.35150729  0.1780886 ]
 [ 0.09178109  0.09530161]], shape=(10, 2), device=gpu, requires_grad=True)

## Batch Norm + GPU

In [15]:
bn = BatchNorm1D(classes).to(device)
bn(linear(X))

Tensor(
[[-0.31661494 -1.31058765]
 [ 2.68352601  1.94354551]
 [-0.88038565  0.77155866]
 [ 0.75780802 -1.17369633]
 [-0.69332619  0.31819888]
 [-0.57831378  0.7957181 ]
 [-0.62720759 -0.1432484 ]
 [-0.24401277 -1.32938502]
 [ 0.14373577  0.0930548 ]
 [-0.24520889  0.03484145]], shape=(10, 2), device=gpu, requires_grad=True)

## ReLU + GPU

In [16]:
relu = Relu()
relu(X)

Tensor(
[[0.58798189 2.16387463 2.33836743 0.         0.        ]
 [1.47063539 0.         0.         0.         0.        ]
 [1.45791414 0.         0.         0.8794434  0.39046668]
 [0.         2.02830774 0.         0.         0.        ]
 [0.         0.         0.         0.30244401 0.58503292]
 [0.         0.         0.41957335 0.88126681 0.        ]
 [0.         0.         0.13749507 0.66154798 0.        ]
 [0.         1.90552133 0.6133612  0.         0.        ]
 [0.         0.         1.79440394 0.         0.        ]
 [1.99816725 0.43343039 0.         0.         0.91340721]], shape=(10, 5), device=gpu, requires_grad=False)

## Linear + ReLU + Batch Norm + GPU

In [17]:
relu(bn(linear(X)))

Tensor(
[[0.         0.        ]
 [2.68352601 1.94354551]
 [0.         0.77155866]
 [0.75780802 0.        ]
 [0.         0.31819888]
 [0.         0.7957181 ]
 [0.         0.        ]
 [0.         0.        ]
 [0.14373577 0.0930548 ]
 [0.         0.03484145]], shape=(10, 2), device=gpu, requires_grad=True)