# Tensor

The **Tensor** is Sorix's fundamental data structure, analogous to **NumPy** arrays, but with the crucial capability to record the history of operations. This tracking is essential for the automatic calculation of **gradients** during the backpropagation process, known as [automatic differentiation(Autograd)](../autograd).


[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/docs/learn/tensor.ipynb)

## Install Sorix

In [31]:
!pip install sorix

zsh:1: command not found: pip


In [32]:
import sorix
import numpy as np
import pandas as pd

## Create a Tensor
A tensor can be initialized from any NumPy array , pandas DataFrame or Python list. 

In [33]:
# from list
a = sorix.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [34]:
#from numpy
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.16399112 0.85496624 0.2920639  0.49900975 0.77389313]
 [0.67184897 0.16597644 0.04879486 0.03832219 0.53913048]
 [0.5380105  0.95508995 0.32806654 0.83901336 0.94824825]
 [0.18825755 0.65056746 0.53132855 0.22983626 0.31488235]
 [0.6761343  0.31198583 0.42449973 0.68457439 0.2520538 ]], shape=(5, 5), device=cpu, requires_grad=False)

In [35]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

## Sorix utils to create tensors

In [36]:
t = sorix.as_tensor([1,2,3])
t

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [37]:
t = sorix.randn(3,4)
t

Tensor(
[[ 1.10020328 -0.79650611  0.78450988 -0.00907493]
 [-1.17643453 -0.44627879 -0.00787046 -1.24932268]
 [-0.07238403  2.72985035 -1.15394118  0.89999772]], shape=(3, 4), device=cpu, requires_grad=False)

In [38]:
t = sorix.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), device=cpu, requires_grad=False)

In [39]:
t = sorix.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), device=cpu, requires_grad=False)

In [40]:
t = sorix.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), device=cpu, requires_grad=False)

In [41]:
t = sorix.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), device=cpu, requires_grad=False)

In [42]:
t = sorix.randint(0,10,(3,4))
t

Tensor(
[[5 6 0 3]
 [3 3 0 8]
 [4 4 9 9]], shape=(3, 4), device=cpu, requires_grad=False)

In [43]:
t = sorix.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), device=cpu, requires_grad=False)

In [44]:
t = sorix.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), device=cpu, requires_grad=False)

In [45]:
t = sorix.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [46]:
t = sorix.randperm(5)
t

Tensor(
[2 0 3 1 4], shape=(5,), device=cpu, requires_grad=False)

## Basic Operations

In [47]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [48]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [49]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [50]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [51]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [52]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

## Slicing

In [53]:
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.62000164 0.67130958 0.26116826 0.60136234 0.02031719]
 [0.5154812  0.71117516 0.95733014 0.92618031 0.1598157 ]
 [0.24634819 0.35514241 0.14543202 0.07272725 0.8752431 ]
 [0.1289894  0.53780597 0.85740244 0.3219446  0.74041199]
 [0.87318355 0.44833643 0.89126092 0.53756009 0.24160895]], shape=(5, 5), device=cpu, requires_grad=False)

In [54]:
a[3,:]

Tensor(
[0.1289894  0.53780597 0.85740244 0.3219446  0.74041199], shape=(5,), device=cpu, requires_grad=False)

In [55]:
a[3,3]

Tensor(
0.3219446045703963, shape=(), device=cpu, requires_grad=False)

In [56]:
a[:,3]

Tensor(
[0.60136234 0.92618031 0.07272725 0.3219446  0.53756009], shape=(5,), device=cpu, requires_grad=False)

## Using GPU

In [57]:
device = 'gpu' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [58]:
a = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
c

Tensor(
[[1.45504608 1.18828319 0.54567181 0.71160792 1.08238965]
 [0.97084798 1.5716228  0.95203572 0.51304775 0.67638717]
 [0.76072463 1.12455433 1.35064991 0.48484223 1.10515691]
 [0.92582087 1.30620971 1.40329954 0.46027527 1.32662203]
 [1.66167195 1.40152719 1.08014019 1.36829579 0.9928954 ]], shape=(5, 5), device=gpu, requires_grad=True)