[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/examples/basics/1-tensor.ipynb)


In [1]:
!pip install "sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop"

zsh:1: command not found: pip


In [2]:
import sorix
import numpy as np
import pandas as pd

# Create a Tensor

In [3]:
# from list
a = sorix.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [4]:
a.shape

(3,)

In [5]:
len(a)

3

In [6]:
#from numpy
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.28092346 0.75146359 0.87447212 0.76594216 0.31226666]
 [0.9436358  0.70415567 0.78794408 0.65786606 0.55500596]
 [0.33068273 0.957704   0.53837725 0.4722785  0.48380784]
 [0.73131031 0.4705965  0.71543723 0.81129202 0.70227026]
 [0.72180409 0.12211265 0.06121499 0.29998376 0.00749783]], shape=(5, 5), device=cpu, requires_grad=False)

In [7]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

In [8]:
# using sorix

In [9]:
t = sorix.as_tensor([1,2,3])
t

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [10]:
t = sorix.randn(3,4)
t

Tensor(
[[ 0.02651174 -0.89552252 -1.14525115  0.31336189]
 [ 0.23632627 -0.73146391 -1.4883811  -0.3693241 ]
 [ 0.60863634 -0.06033078  0.33069665  0.21576652]], shape=(3, 4), device=cpu, requires_grad=False)

In [11]:
t = sorix.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), device=cpu, requires_grad=False)

In [12]:
t = sorix.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), device=cpu, requires_grad=False)

In [13]:
t = sorix.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), device=cpu, requires_grad=False)

In [14]:
t = sorix.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), device=cpu, requires_grad=False)

In [15]:
t = sorix.randint(0,10,(3,4))
t

Tensor(
[[0 3 1 8]
 [2 3 8 7]
 [3 1 5 3]], shape=(3, 4), device=cpu, requires_grad=False)

In [16]:
t = sorix.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), device=cpu, requires_grad=False)

In [17]:
t = sorix.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), device=cpu, requires_grad=False)

In [18]:
t = sorix.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [19]:
t = sorix.randperm(5)
t

Tensor(
[4 1 3 2 0], shape=(5,), device=cpu, requires_grad=False)

# Basic Operations

In [20]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [21]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [22]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [23]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [24]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [25]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [26]:
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.92336331 0.68673055 0.77544605 0.36723032 0.67482779]
 [0.30458672 0.41185972 0.06209699 0.24396813 0.65078411]
 [0.01095647 0.55915119 0.05275689 0.98511083 0.27624703]
 [0.53005892 0.79170857 0.99680674 0.4869889  0.78385095]
 [0.31062682 0.4327899  0.40077475 0.09330501 0.33579877]], shape=(5, 5), device=cpu, requires_grad=False)

In [27]:
a[3,:]

Tensor(
[0.53005892 0.79170857 0.99680674 0.4869889  0.78385095], shape=(5,), device=cpu, requires_grad=False)

In [28]:
a[3,3]

Tensor(
0.48698890456434085, shape=(), device=cpu, requires_grad=False)

In [29]:
a[:,3]

Tensor(
[0.36723032 0.24396813 0.98511083 0.4869889  0.09330501], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [30]:
a = sorix.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [31]:
b =sorix.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [32]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
[Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)]
grad(a) [0 0 0]
grad(b) [0 0 0]


In [33]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [34]:
with sorix.no_grad():
    a = sorix.tensor([1,2,3], requires_grad=True)
    b = sorix.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

[]

# Using GPU

In [35]:
device = 'gpu' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [36]:
a = sorix.tensor(np.random.rand(5,5), device=device)
b = sorix.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.40664906 1.15114595 0.90456634 0.92108748 0.71102074]
 [0.35801649 1.01342608 1.0053445  0.62635711 1.65927723]
 [0.31127442 0.91311539 0.90891917 0.59172076 1.57029185]
 [0.8860267  1.3627148  0.98706443 0.6999196  1.60164148]
 [0.75623909 0.59822662 0.99845252 0.60544863 0.93439987]], shape=(5, 5), device=gpu, requires_grad=False)
[]
gpu


In [37]:
a = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.89386259 0.62293245 0.94719665 1.18345976 1.27521014]
 [0.76480062 1.02244469 1.4531735  1.19541198 1.27450673]
 [0.41912489 1.44803451 0.94885152 1.0944947  1.34400486]
 [1.24868022 0.9278844  0.86707511 0.63535178 0.87811857]
 [0.54134896 0.82290007 1.39329326 1.45967453 0.56246597]], shape=(5, 5), device=gpu, requires_grad=True)
[Tensor(
[[0.62777446 0.09472604 0.93324202 0.38338362 0.84388196]
 [0.00428038 0.8904601  0.79276915 0.89137567 0.41769574]
 [0.3137353  0.99088183 0.23697458 0.65099263 0.4833127 ]
 [0.8028177  0.38656772 0.29129584 0.27077164 0.54392738]
 [0.26143035 0.51865566 0.78065695 0.61237395 0.23536121]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.26608813 0.52820641 0.01395462 0.80007613 0.43132818]
 [0.76052024 0.13198458 0.66040435 0.30403631 0.85681099]
 [0.10538959 0.45715268 0.71187694 0.44350207 0.86069216]
 [0.44586252 0.54131668 0.57577926 0.36458014 0.3341912 ]
 [0.27991861 0.30424441 0.61263631 0.84730058 0.32710476]], shape=