[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/examples/basics/1-tensor.ipynb)


In [1]:
!pip install "sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop"

zsh:1: command not found: pip


In [2]:
import sorix
import numpy as np
import pandas as pd

# Create a Tensor

In [3]:
# from list
a = sorix.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [4]:
a.shape

(3,)

In [5]:
len(a)

3

In [6]:
#from numpy
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.37399589 0.19649839 0.30243269 0.70122509 0.9580488 ]
 [0.55729552 0.41936393 0.1496817  0.93341833 0.70631968]
 [0.65274073 0.43823923 0.22185592 0.007254   0.07164629]
 [0.94769136 0.07965996 0.49907957 0.44509893 0.76914875]
 [0.98666442 0.6525136  0.00795356 0.77332442 0.0028888 ]], shape=(5, 5), device=cpu, requires_grad=False)

In [7]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

In [8]:
# using sorix

In [9]:
t = sorix.as_tensor([1,2,3])
t

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [10]:
t = sorix.randn(3,4)
t

Tensor(
[[ 0.71688057 -0.19874503 -0.35169322  0.82470856]
 [-1.4631612   0.53224639 -1.72869424  0.65746864]
 [ 0.67186086  0.39112483  0.60633064 -0.26629189]], shape=(3, 4), device=cpu, requires_grad=False)

In [11]:
t = sorix.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), device=cpu, requires_grad=False)

In [12]:
t = sorix.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), device=cpu, requires_grad=False)

In [13]:
t = sorix.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), device=cpu, requires_grad=False)

In [14]:
t = sorix.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), device=cpu, requires_grad=False)

In [15]:
t = sorix.randint(0,10,(3,4))
t

Tensor(
[[4 9 1 4]
 [1 8 3 9]
 [9 4 1 0]], shape=(3, 4), device=cpu, requires_grad=False)

In [16]:
t = sorix.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), device=cpu, requires_grad=False)

In [17]:
t = sorix.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), device=cpu, requires_grad=False)

In [18]:
t = sorix.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [19]:
t = sorix.randperm(5)
t

Tensor(
[2 0 1 4 3], shape=(5,), device=cpu, requires_grad=False)

# Basic Operations

In [20]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [21]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [22]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [23]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [24]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [25]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [26]:
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.6967138  0.43596383 0.43996049 0.40141415 0.4515114 ]
 [0.38002216 0.36647835 0.09117444 0.57971815 0.83406303]
 [0.65263256 0.72699751 0.8596539  0.42020987 0.46402863]
 [0.46986571 0.62731168 0.10919792 0.90870898 0.79108453]
 [0.50114497 0.49551479 0.23088768 0.50319652 0.57365659]], shape=(5, 5), device=cpu, requires_grad=False)

In [27]:
a[3,:]

Tensor(
[0.46986571 0.62731168 0.10919792 0.90870898 0.79108453], shape=(5,), device=cpu, requires_grad=False)

In [28]:
a[3,3]

Tensor(
0.9087089778799242, shape=(), device=cpu, requires_grad=False)

In [29]:
a[:,3]

Tensor(
[0.40141415 0.57971815 0.42020987 0.90870898 0.50319652], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [30]:
a = sorix.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [31]:
b =sorix.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [32]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
[Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)]
grad(a) [0 0 0]
grad(b) [0 0 0]


In [33]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [34]:
with sorix.no_grad():
    a = sorix.tensor([1,2,3], requires_grad=True)
    b = sorix.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

[]

# Using GPU

In [35]:
device = 'gpu' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [36]:
a = sorix.tensor(np.random.rand(5,5), device=device)
b = sorix.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.4101917  0.64202619 1.14049038 0.92903638 1.41747293]
 [1.6597381  1.30715243 1.30986569 0.86842767 0.87778111]
 [1.28018672 1.04680671 1.73406969 1.07921462 1.66488324]
 [1.31221711 1.04145782 0.9998012  1.92287338 0.34610239]
 [1.10654948 0.35705694 1.41706766 1.16865167 0.78233984]], shape=(5, 5), device=gpu, requires_grad=False)
[]
gpu


In [37]:
a = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.27806444 1.57947015 0.33019191 1.39573979 1.22990431]
 [0.57088112 1.35815024 1.46592682 0.77876535 1.03271084]
 [0.93546053 0.72290763 0.01949037 1.42346045 1.39994648]
 [1.65571953 0.61387884 0.56322479 1.09438814 1.23824168]
 [1.20684304 1.33278915 1.48910119 1.34793832 1.32637179]], shape=(5, 5), device=gpu, requires_grad=True)
[Tensor(
[[0.60546882 0.99342721 0.08218376 0.83936157 0.27586493]
 [0.25220502 0.76266604 0.55008736 0.13729578 0.59852002]
 [0.32039141 0.07106275 0.01635042 0.67009456 0.46991461]
 [0.94835993 0.18845118 0.34399779 0.40539695 0.84211198]
 [0.32814044 0.83636744 0.90827008 0.67017487 0.48849169]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.67259562 0.58604294 0.24800815 0.55637822 0.95403937]
 [0.3186761  0.5954842  0.91583946 0.64146957 0.43419082]
 [0.61506912 0.65184489 0.00313995 0.75336589 0.93003187]
 [0.7073596  0.42542765 0.21922701 0.68899119 0.39612971]
 [0.87870261 0.49642171 0.5808311  0.67776345 0.83788011]], shape=