[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/examples/basics/1-tensor.ipynb)


In [1]:
!pip install "sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop"

zsh:1: command not found: pip


In [2]:
import sorix
import numpy as np
import pandas as pd

# Create a Tensor

In [3]:
# from list
a = sorix.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [4]:
a.shape

(3,)

In [5]:
len(a)

3

In [6]:
#from numpy
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.88940925 0.0096972  0.96500784 0.85311095 0.42724716]
 [0.7016169  0.64276087 0.78517358 0.82488133 0.09213998]
 [0.27334709 0.85438475 0.37830478 0.54929228 0.19072391]
 [0.22725324 0.4698099  0.63320615 0.124535   0.56095844]
 [0.58356912 0.01238972 0.39621296 0.589053   0.6951893 ]], shape=(5, 5), device=cpu, requires_grad=False)

In [7]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

In [8]:
# using sorix

In [9]:
t = sorix.as_tensor([1,2,3])
t

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [10]:
t = sorix.randn(3,4)
t

Tensor(
[[ 0.81970668  0.9653112   1.81373758 -0.48484559]
 [-1.75116337 -1.11163623 -1.1291422   0.51349907]
 [ 0.23476452 -1.90231636 -0.67284453 -0.61183171]], shape=(3, 4), device=cpu, requires_grad=False)

In [11]:
t = sorix.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), device=cpu, requires_grad=False)

In [12]:
t = sorix.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), device=cpu, requires_grad=False)

In [13]:
t = sorix.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), device=cpu, requires_grad=False)

In [14]:
t = sorix.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), device=cpu, requires_grad=False)

In [15]:
t = sorix.randint(0,10,(3,4))
t

Tensor(
[[8 4 0 8]
 [3 9 8 8]
 [3 8 9 8]], shape=(3, 4), device=cpu, requires_grad=False)

In [16]:
t = sorix.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), device=cpu, requires_grad=False)

In [17]:
t = sorix.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), device=cpu, requires_grad=False)

In [18]:
t = sorix.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [19]:
t = sorix.randperm(5)
t

Tensor(
[0 4 1 2 3], shape=(5,), device=cpu, requires_grad=False)

# Basic Operations

In [20]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [21]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [22]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [23]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [24]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [25]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [26]:
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[2.08407334e-01 2.56151909e-01 9.18421358e-01 9.36649996e-01
  9.45427908e-01]
 [9.80726156e-02 9.25486429e-01 3.79427539e-01 8.90629703e-01
  6.13399364e-01]
 [9.84771559e-01 1.71610060e-01 7.36123886e-02 7.76762192e-04
  4.16186605e-01]
 [5.96088530e-01 2.42154776e-01 8.50368291e-01 2.95490506e-01
  4.59679883e-01]
 [9.21401514e-01 1.06074791e-01 7.08986919e-03 4.68003043e-01
  5.43875180e-01]], shape=(5, 5), device=cpu, requires_grad=False)

In [27]:
a[3,:]

Tensor(
[0.59608853 0.24215478 0.85036829 0.29549051 0.45967988], shape=(5,), device=cpu, requires_grad=False)

In [28]:
a[3,3]

Tensor(
0.2954905056202939, shape=(), device=cpu, requires_grad=False)

In [29]:
a[:,3]

Tensor(
[9.36649996e-01 8.90629703e-01 7.76762192e-04 2.95490506e-01
 4.68003043e-01], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [30]:
a = sorix.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [31]:
b =sorix.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [32]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
[Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)]
grad(a) [0 0 0]
grad(b) [0 0 0]


In [33]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [34]:
with sorix.no_grad():
    a = sorix.tensor([1,2,3], requires_grad=True)
    b = sorix.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

[]

# Using GPU

In [35]:
device = 'gpu' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [36]:
a = sorix.tensor(np.random.rand(5,5), device=device)
b = sorix.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.96628078 0.93330665 0.6105737  0.85021859 1.20459194]
 [1.41147757 0.54696675 1.2008804  0.96975154 0.6128279 ]
 [1.35504276 1.61944193 0.46952585 1.18116663 0.33020243]
 [1.6872361  0.56164273 0.85470686 1.16474397 1.70931082]
 [0.91364929 0.60238692 1.51267372 0.75183814 0.32654958]], shape=(5, 5), device=gpu, requires_grad=False)
[]
gpu


In [37]:
a = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.53680694 0.81720379 1.30818099 1.52160565 1.63990954]
 [1.5740084  0.9935478  1.34105475 0.85007392 0.97663011]
 [1.07656293 0.93336754 1.04608803 0.82206175 0.62163944]
 [1.64862873 1.12582551 1.29770996 0.82071078 1.51725933]
 [0.39435762 1.32626185 0.65147943 0.76452342 1.89053785]], shape=(5, 5), device=gpu, requires_grad=True)
[Tensor(
[[0.65490844 0.04561791 0.99298382 0.63912491 0.84430481]
 [0.7799283  0.57776194 0.80938349 0.40237797 0.11979724]
 [0.30061374 0.06554442 0.94650819 0.37568953 0.1920208 ]
 [0.67186383 0.6833463  0.74767989 0.27098007 0.64172457]
 [0.05539309 0.75452855 0.21624153 0.5492125  0.94389503]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.88189851 0.77158588 0.31519718 0.88248074 0.79560474]
 [0.7940801  0.41578586 0.53167126 0.44769595 0.85683287]
 [0.77594919 0.86782312 0.09957984 0.44637221 0.42961864]
 [0.9767649  0.44247921 0.55003008 0.54973071 0.87553476]
 [0.33896453 0.5717333  0.43523791 0.21531092 0.94664282]], shape=