[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/main/examples/basics/1-tensor.ipynb)


In [ ]:
#!pip install sorix

In [2]:
import sorix as sx
import numpy as np
import pandas as pd

# Create a Tensor

In [3]:
# from list
a = sx.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [4]:
a.shape

(3,)

In [5]:
len(a)

3

In [6]:
#from numpy
a = sx.tensor(np.random.rand(5,5))
a

Tensor(
[[0.78813137 0.03779057 0.22824564 0.05896078 0.03265621]
 [0.96842247 0.09965155 0.45020797 0.12791178 0.06632382]
 [0.93998969 0.76494942 0.13141222 0.64511171 0.4229731 ]
 [0.34743447 0.57063552 0.42237496 0.58394582 0.21704756]
 [0.92722097 0.11521139 0.66698874 0.36369923 0.53666953]], shape=(5, 5), device=cpu, requires_grad=False)

In [7]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sx.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

In [8]:
# using sorix

In [9]:
t = sx.as_tensor([1,2,3])
t

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [10]:
t = sx.randn(3,4)
t

Tensor(
[[-1.40005522  0.57080938  0.46956603  0.29732309]
 [-0.477271    0.92518948 -0.56429461 -0.41290738]
 [-0.49930023 -1.25793339  0.23511013  1.03720071]], shape=(3, 4), device=cpu, requires_grad=False)

In [11]:
t = sx.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), device=cpu, requires_grad=False)

In [12]:
t = sx.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), device=cpu, requires_grad=False)

In [13]:
t = sx.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), device=cpu, requires_grad=False)

In [14]:
t = sx.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), device=cpu, requires_grad=False)

In [15]:
t = sx.randint(0,10,(3,4))
t

Tensor(
[[9 8 0 3]
 [0 2 1 4]
 [7 3 5 8]], shape=(3, 4), device=cpu, requires_grad=False)

In [16]:
t = sx.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), device=cpu, requires_grad=False)

In [17]:
t = sx.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), device=cpu, requires_grad=False)

In [18]:
t = sx.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [19]:
t = sx.randperm(5)
t

Tensor(
[4 1 0 2 3], shape=(5,), device=cpu, requires_grad=False)

# Basic Operations

In [20]:
a = sx.tensor([1,2,3])
b = sx.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [21]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [22]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [23]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [24]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [25]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [26]:
a = sx.tensor(np.random.rand(5,5))
a

Tensor(
[[0.39120523 0.96529118 0.6778492  0.13640881 0.43819848]
 [0.63729949 0.32643487 0.62799089 0.76869534 0.96555682]
 [0.54878059 0.55547991 0.15362911 0.11841103 0.91359885]
 [0.12308988 0.92094211 0.48578905 0.69297574 0.6013773 ]
 [0.9186708  0.71764683 0.53598776 0.41803441 0.09950187]], shape=(5, 5), device=cpu, requires_grad=False)

In [27]:
a[3,:]

Tensor(
[0.12308988 0.92094211 0.48578905 0.69297574 0.6013773 ], shape=(5,), device=cpu, requires_grad=False)

In [28]:
a[3,3]

Tensor(
0.6929757447781624, shape=(), device=cpu, requires_grad=False)

In [29]:
a[:,3]

Tensor(
[0.13640881 0.76869534 0.11841103 0.69297574 0.41803441], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [30]:
a = sx.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [31]:
b =sx.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [32]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
[Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)]
grad(a) [0 0 0]
grad(b) [0 0 0]


In [33]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [34]:
with sx.no_grad():
    a = sx.tensor([1,2,3], requires_grad=True)
    b = sx.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

[]

# Using GPU

In [35]:
device = 'gpu' if sx.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [36]:
a = sx.tensor(np.random.rand(5,5), device=device)
b = sx.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.24121706 0.7602503  0.44674509 0.37479669 0.81777613]
 [0.24624607 1.42766419 0.98178083 0.79738418 1.20425615]
 [0.64131372 0.53529128 1.84455867 0.92773633 0.5561504 ]
 [0.65410468 1.66663127 0.99282143 0.40548397 0.40293902]
 [0.56417797 0.23973362 0.53254864 0.55758884 0.6122305 ]], shape=(5, 5), device=gpu, requires_grad=False)
[]
gpu


In [37]:
a = sx.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = sx.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.06631886 0.19427253 0.25359629 0.82559971 0.80810209]
 [0.69357085 1.06636595 1.26370901 1.27163226 1.16044555]
 [0.84673404 1.15708544 0.82797771 1.25275683 1.00118966]
 [0.92693653 1.70058635 1.21281368 1.69064038 0.85305474]
 [1.13883892 1.0505328  1.19685374 0.73814206 0.65414803]], shape=(5, 5), device=gpu, requires_grad=True)
[Tensor(
[[0.86816629 0.06551906 0.21563053 0.08103199 0.23098284]
 [0.58085238 0.4729961  0.7921607  0.65719955 0.9980474 ]
 [0.52214386 0.23983855 0.52192943 0.35830781 0.5115543 ]
 [0.06457418 0.95817097 0.21368449 0.71946382 0.02286391]
 [0.37268213 0.48715795 0.49962496 0.56737527 0.20897555]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.19815257 0.12875347 0.03796576 0.74456771 0.57711925]
 [0.11271847 0.59336985 0.47154831 0.61443271 0.16239816]
 [0.32459018 0.91724689 0.30604828 0.89444902 0.48963536]
 [0.86236235 0.74241539 0.99912919 0.97117657 0.83019083]
 [0.76615679 0.56337485 0.69722878 0.17076679 0.44517248]], shape=