[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/examples/basics/1-tensor.ipynb)


In [1]:
!pip install "sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop"

zsh:1: command not found: pip


In [2]:
import sorix
import numpy as np
import pandas as pd

# Create a Tensor

In [3]:
# from list
a = sorix.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [4]:
a.shape

(3,)

In [5]:
len(a)

3

In [6]:
#from numpy
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.0220421  0.00127101 0.54604194 0.94293658 0.05594837]
 [0.50918008 0.62210128 0.89692786 0.84424951 0.2598907 ]
 [0.999589   0.92737476 0.81083098 0.07518408 0.75837337]
 [0.16188555 0.08547034 0.46886043 0.97008058 0.98521487]
 [0.162045   0.46566789 0.93764773 0.25518066 0.32053246]], shape=(5, 5), device=cpu, requires_grad=False)

In [7]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

In [8]:
# using sorix

In [9]:
t = sorix.as_tensor([1,2,3])
t

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [10]:
t = sorix.randn(3,4)
t

Tensor(
[[ 2.20389681  1.87754305 -0.07592847 -1.29793342]
 [-1.11155282 -0.40710316  1.95516755 -0.52663931]
 [ 0.60598815  2.0081271   0.30975999 -0.12749121]], shape=(3, 4), device=cpu, requires_grad=False)

In [11]:
t = sorix.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), device=cpu, requires_grad=False)

In [12]:
t = sorix.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), device=cpu, requires_grad=False)

In [13]:
t = sorix.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), device=cpu, requires_grad=False)

In [14]:
t = sorix.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), device=cpu, requires_grad=False)

In [15]:
t = sorix.randint(0,10,(3,4))
t

Tensor(
[[0 5 0 8]
 [5 0 6 6]
 [6 3 5 4]], shape=(3, 4), device=cpu, requires_grad=False)

In [16]:
t = sorix.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), device=cpu, requires_grad=False)

In [17]:
t = sorix.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), device=cpu, requires_grad=False)

In [18]:
t = sorix.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [19]:
t = sorix.randperm(5)
t

Tensor(
[4 2 3 1 0], shape=(5,), device=cpu, requires_grad=False)

# Basic Operations

In [20]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [21]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [22]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [23]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [24]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [25]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [26]:
a = sorix.tensor(np.random.rand(5,5))
a

Tensor(
[[0.95647732 0.0912886  0.60875624 0.25310418 0.27970823]
 [0.84058344 0.63556354 0.06032527 0.35512701 0.29067583]
 [0.34677695 0.02044212 0.61513835 0.03405813 0.18997455]
 [0.48089267 0.00993867 0.02723141 0.11280564 0.59125279]
 [0.09664577 0.12046393 0.43077258 0.40224178 0.28533882]], shape=(5, 5), device=cpu, requires_grad=False)

In [27]:
a[3,:]

Tensor(
[0.48089267 0.00993867 0.02723141 0.11280564 0.59125279], shape=(5,), device=cpu, requires_grad=False)

In [28]:
a[3,3]

Tensor(
0.11280564313549546, shape=(), device=cpu, requires_grad=False)

In [29]:
a[:,3]

Tensor(
[0.25310418 0.35512701 0.03405813 0.11280564 0.40224178], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [30]:
a = sorix.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [31]:
b =sorix.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [32]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
[Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)]
grad(a) [0 0 0]
grad(b) [0 0 0]


In [33]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [34]:
with sorix.no_grad():
    a = sorix.tensor([1,2,3], requires_grad=True)
    b = sorix.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

[]

# Using GPU

In [35]:
device = 'gpu' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [36]:
a = sorix.tensor(np.random.rand(5,5), device=device)
b = sorix.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.4238559  1.15228805 0.39898489 0.99956357 1.11329193]
 [0.37458925 0.92648005 1.65757353 0.34825988 0.94726769]
 [0.71864733 1.38773873 1.38208872 0.52279266 0.84698073]
 [0.40775169 0.52375746 1.63726059 0.49725724 1.01882152]
 [0.65406287 1.25581404 1.41183575 0.81044708 0.70258863]], shape=(5, 5), device=gpu, requires_grad=False)
[]
gpu


In [37]:
a = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = sorix.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.82863099 0.60403152 1.24894125 0.54637815 0.56726651]
 [1.62050567 0.84177567 1.44320116 1.37707008 0.6645631 ]
 [0.41258761 1.17277335 0.94144948 0.84324373 0.68349264]
 [1.11926182 1.71529161 0.98553416 0.59605809 1.87216964]
 [1.75011717 1.39987745 1.17041214 0.77916671 1.2732568 ]], shape=(5, 5), device=gpu, requires_grad=True)
[Tensor(
[[0.95110834 0.37804211 0.98341826 0.44842378 0.05709942]
 [0.80218275 0.3771599  0.56972549 0.52888363 0.18620109]
 [0.3841794  0.25341431 0.55188845 0.65629784 0.10895926]
 [0.51683194 0.84163235 0.73219984 0.16063536 0.99456217]
 [0.78054793 0.93629785 0.65205959 0.62734653 0.95198752]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.87752265 0.22598941 0.26552299 0.09795436 0.51016709]
 [0.81832292 0.46461577 0.87347566 0.84818645 0.47836201]
 [0.02840821 0.91935904 0.38956103 0.18694588 0.57453339]
 [0.60242989 0.87365925 0.25333432 0.43542273 0.87760747]
 [0.96956924 0.4635796  0.51835255 0.15182019 0.32126927]], shape=