[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/examples/basics/2-layers.ipynb)

In [1]:
!pip install "sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop"

zsh:1: command not found: pip


In [2]:
import numpy as np
from sorix import tensor
from sorix.nn import Relu,Linear,BatchNorm1D
import sorix

In [3]:
features = 5
classes = 2
examples = 10

In [4]:
# create random data
X = tensor(np.random.randn(examples, features))
X

Tensor(
[[-0.48594222  0.20677561  0.42565439  0.07748361  0.19287567]
 [ 0.67315566 -0.79199502 -1.23024536 -0.56780411 -1.33028555]
 [-1.33843538  0.04374422 -1.44857163 -0.00760165 -0.71882167]
 [ 0.02169972 -0.95188567 -0.34896603 -2.09219575 -0.66064534]
 [-1.59877358 -1.32468555  0.66410523  0.69569964 -1.9868028 ]
 [ 0.29000665 -0.42269424 -1.8075928  -0.29014177 -1.27478681]
 [-1.31932015 -0.6949815  -0.44573447  1.38394699  0.32550933]
 [-0.88421416 -0.85807732  0.57674665  1.6080925  -0.12623315]
 [-0.1629156  -2.15008334 -0.1151611  -0.28390963  0.39744731]
 [-1.97016385 -0.30037512  0.49587062  0.34757145  0.4821836 ]], shape=(10, 5), device=cpu, requires_grad=False)

# Linear

In [5]:
linear = Linear(features,classes)
linear.W,linear.b

(Tensor(
 [[ 0.25071158  0.48714601]
  [-0.33605762 -0.61613452]
  [ 0.95121854  0.83252505]
  [ 0.55347509  0.4142944 ]
  [-0.38324971  0.80630665]], shape=(5, 2), device=cpu, requires_grad=True),
 Tensor(
 [[0. 0.]], shape=(1, 2), device=cpu, requires_grad=True))

In [6]:
linear(X)

Tensor(
[[ 0.18253619  0.1778595 ]
 [-0.53974219 -1.51616566]
 [-1.45688914 -2.46767796]
 [-0.91140024 -1.09293013]
 [ 1.82254285 -0.72351528]
 [-1.1766827  -2.25122738]
 [ 0.12002294  0.25023727]
 [ 1.55371076  1.14254679]
 [ 0.26270523  1.35234461]
 [ 0.08625721  0.17092349]], shape=(10, 2), device=cpu, requires_grad=True)

# Batch Norm

In [7]:
bn = BatchNorm1D(classes)
bn.gamma,bn.beta

(Tensor(
 [[1. 1.]], shape=(1, 2), device=cpu, requires_grad=True),
 Tensor(
 [[0. 0.]], shape=(1, 2), device=cpu, requires_grad=True))

In [8]:
bn(linear(X))

Tensor(
[[ 0.18379257  0.5329729 ]
 [-0.52145806 -0.80735181]
 [-1.41698321 -1.56019507]
 [-0.88435424 -0.47248486]
 [ 1.78513596 -0.18020121]
 [-1.14338265 -1.38893784]
 [ 0.12275306  0.5902387 ]
 [ 1.5226416   1.29624031]
 [ 0.26207161  1.46223383]
 [ 0.08978336  0.52748507]], shape=(10, 2), device=cpu, requires_grad=True)

# ReLU

In [9]:
relu = Relu()
relu(X)

Tensor(
[[0.         0.20677561 0.42565439 0.07748361 0.19287567]
 [0.67315566 0.         0.         0.         0.        ]
 [0.         0.04374422 0.         0.         0.        ]
 [0.02169972 0.         0.         0.         0.        ]
 [0.         0.         0.66410523 0.69569964 0.        ]
 [0.29000665 0.         0.         0.         0.        ]
 [0.         0.         0.         1.38394699 0.32550933]
 [0.         0.         0.57674665 1.6080925  0.        ]
 [0.         0.         0.         0.         0.39744731]
 [0.         0.         0.49587062 0.34757145 0.4821836 ]], shape=(10, 5), device=cpu, requires_grad=False)

# Linear + ReLU

In [10]:
relu(linear(X))

Tensor(
[[0.18253619 0.1778595 ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [1.82254285 0.        ]
 [0.         0.        ]
 [0.12002294 0.25023727]
 [1.55371076 1.14254679]
 [0.26270523 1.35234461]
 [0.08625721 0.17092349]], shape=(10, 2), device=cpu, requires_grad=True)

# Linear + BatchNorm + ReLU

In [11]:
relu(bn(linear(X)))

Tensor(
[[0.18379257 0.5329729 ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [1.78513596 0.        ]
 [0.         0.        ]
 [0.12275306 0.5902387 ]
 [1.5226416  1.29624031]
 [0.26207161 1.46223383]
 [0.08978336 0.52748507]], shape=(10, 2), device=cpu, requires_grad=True)

Without bias

In [12]:
linear = Linear(features,classes,bias=False)
relu(bn(linear(X)))

Tensor(
[[0.23904369 0.1779223 ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.19077019 0.12551161]
 [0.         0.        ]
 [1.05951897 1.1476031 ]
 [1.56410386 0.85524715]
 [0.9386184  0.38467373]
 [0.52156832 1.43988683]], shape=(10, 2), device=cpu, requires_grad=True)

# Using GPU

In [13]:
device = 'gpu' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

# Linear

In [14]:
features = 5
classes = 2
examples = 10

X = tensor(np.random.randn(examples, features), device=device)
linear = Linear(features,classes).to(device)
linear(X)

Tensor(
[[ 0.6713594   0.91666288]
 [-1.65042091 -0.47937574]
 [ 0.97963412  0.29583894]
 [-0.36607553 -0.39666538]
 [ 1.41973146  0.82391642]
 [-0.27794028  0.91926435]
 [ 2.52123003 -0.02098595]
 [-2.35360265 -0.75056718]
 [-0.18716636 -0.24815463]
 [ 1.00159651 -0.06064575]], shape=(10, 2), device=gpu, requires_grad=True)

# Batch Norm

In [15]:
bn = BatchNorm1D(classes).to(device)
bn(linear(X))

Tensor(
[[ 0.35962031  1.407302  ]
 [-1.32537976 -0.99819079]
 [ 0.58334644  0.33756976]
 [-0.39328379 -0.85567382]
 [ 0.90274102  1.247492  ]
 [-0.32932085  1.41178456]
 [ 1.70213843 -0.20834634]
 [-1.83570421 -1.4654766 ]
 [-0.26344293 -0.59977723]
 [ 0.59928534 -0.27668354]], shape=(10, 2), device=gpu, requires_grad=True)

# ReLU

In [16]:
relu = Relu()
relu(X)

Tensor(
[[0.         0.5860021  0.         0.28530006 0.        ]
 [0.         0.         0.         0.37312334 1.16943056]
 [0.90777748 0.         0.         0.         0.        ]
 [0.36656173 0.         1.47969103 0.         1.29345769]
 [0.         0.         0.34552412 0.         0.        ]
 [0.         0.         0.88324194 0.31548754 0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.1570195  0.05772742 0.55415927 1.11812266 1.52984663]
 [0.21960764 0.         0.15598548 0.         1.03600345]
 [0.25485916 0.         0.         0.         0.01316576]], shape=(10, 5), device=gpu, requires_grad=False)

# Linear + ReLU + Batch Norm

In [17]:
relu(bn(linear(X)))

Tensor(
[[0.35962031 1.407302  ]
 [0.         0.        ]
 [0.58334644 0.33756976]
 [0.         0.        ]
 [0.90274102 1.247492  ]
 [0.         1.41178456]
 [1.70213843 0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.59928534 0.        ]], shape=(10, 2), device=gpu, requires_grad=True)