[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/examples/basics/2-layers.ipynb)

In [1]:
!pip install "sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop"

zsh:1: command not found: pip


In [2]:
import numpy as np
from sorix import tensor
from sorix.nn import Relu,Linear,BatchNorm1D
import sorix

In [3]:
features = 5
classes = 2
examples = 10

In [4]:
# create random data
X = tensor(np.random.randn(examples, features))
X

Tensor(
[[-0.7645274   0.11031426 -1.80640296 -0.30260984 -1.05184342]
 [ 0.66969626 -0.27608716 -2.20032213 -1.04568664  0.54842168]
 [-0.69823209  0.63608031 -1.1553431  -0.95048886 -1.57035949]
 [-0.50222303  1.16050161 -0.87445784 -2.13083781  0.66935913]
 [-0.14206545 -0.69912015 -0.37224779  1.99723135  0.68110058]
 [-1.2563066  -1.59581922 -1.39625669  0.35208002 -1.4148969 ]
 [-0.40224573  1.30979286 -0.38131647 -0.85940871 -0.27202803]
 [-1.14313365  1.11043574 -0.19624218  0.2504245  -0.422679  ]
 [ 1.73013322  0.32130227  0.03180584 -0.48978878 -0.56991418]
 [ 1.87884682 -0.8929756  -0.85686965  0.59177927 -0.32001781]], shape=(10, 5), device=cpu, requires_grad=False)

# Linear

In [5]:
linear = Linear(features,classes)
linear.W,linear.b

(Tensor(
 [[-0.95227908  0.4718314 ]
  [-0.13955674  0.13709889]
  [ 0.31288212  0.20734511]
  [-1.05468636 -0.08194782]
  [ 0.47114137 -0.97189457]], shape=(5, 2), device=cpu, requires_grad=True),
 Tensor(
 [[0. 0.]], shape=(1, 2), device=cpu, requires_grad=True))

In [6]:
linear(X)

Tensor(
[[-0.02895133  0.32692625]
 [ 0.0736062  -0.62540985]
 [ 0.47726263  1.1223177 ]
 [ 2.60542679 -0.73510465]
 [-1.66917479 -1.06569001]
 [-0.0557524   0.2452215 ]
 [ 0.85919566  0.24552411]
 [ 0.40895194 -0.03753902]
 [-1.4343947   1.46100977]
 [-2.70758012  0.84893379]], shape=(10, 2), device=cpu, requires_grad=True)

# Batch Norm

In [7]:
bn = BatchNorm1D(classes)
bn.gamma,bn.beta

(Tensor(
 [[1. 1.]], shape=(1, 2), device=cpu, requires_grad=True),
 Tensor(
 [[0. 0.]], shape=(1, 2), device=cpu, requires_grad=True))

In [8]:
bn(linear(X))

Tensor(
[[ 0.08380546  0.19001571]
 [ 0.15652654 -1.03014561]
 [ 0.44274961  1.20909487]
 [ 1.95177968 -1.17068985]
 [-1.07923757 -1.59424563]
 [ 0.06480147  0.08533316]
 [ 0.71356915  0.08572087]
 [ 0.39431215 -0.27694803]
 [-0.91276065  1.64303722]
 [-1.81554584  0.85882728]], shape=(10, 2), device=cpu, requires_grad=True)

# ReLU

In [9]:
relu = Relu()
relu(X)

Tensor(
[[0.         0.11031426 0.         0.         0.        ]
 [0.66969626 0.         0.         0.         0.54842168]
 [0.         0.63608031 0.         0.         0.        ]
 [0.         1.16050161 0.         0.         0.66935913]
 [0.         0.         0.         1.99723135 0.68110058]
 [0.         0.         0.         0.35208002 0.        ]
 [0.         1.30979286 0.         0.         0.        ]
 [0.         1.11043574 0.         0.2504245  0.        ]
 [1.73013322 0.32130227 0.03180584 0.         0.        ]
 [1.87884682 0.         0.         0.59177927 0.        ]], shape=(10, 5), device=cpu, requires_grad=False)

# Linear + ReLU

In [10]:
relu(linear(X))

Tensor(
[[0.         0.32692625]
 [0.0736062  0.        ]
 [0.47726263 1.1223177 ]
 [2.60542679 0.        ]
 [0.         0.        ]
 [0.         0.2452215 ]
 [0.85919566 0.24552411]
 [0.40895194 0.        ]
 [0.         1.46100977]
 [0.         0.84893379]], shape=(10, 2), device=cpu, requires_grad=True)

# Linear + BatchNorm + ReLU

In [11]:
relu(bn(linear(X)))

Tensor(
[[0.08380546 0.19001571]
 [0.15652654 0.        ]
 [0.44274961 1.20909487]
 [1.95177968 0.        ]
 [0.         0.        ]
 [0.06480147 0.08533316]
 [0.71356915 0.08572087]
 [0.39431215 0.        ]
 [0.         1.64303722]
 [0.         0.85882728]], shape=(10, 2), device=cpu, requires_grad=True)

Without bias

In [12]:
linear = Linear(features,classes,bias=False)
relu(bn(linear(X)))

Tensor(
[[0.         0.        ]
 [1.08136303 1.00213593]
 [0.         0.        ]
 [0.70043164 0.70952632]
 [1.07730523 0.07179409]
 [1.67199019 0.        ]
 [0.         0.10042723]
 [0.         0.        ]
 [0.         1.32437817]
 [0.         1.15565228]], shape=(10, 2), device=cpu, requires_grad=True)

# Using GPU

In [13]:
device = 'gpu' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

# Linear

In [14]:
features = 5
classes = 2
examples = 10

X = tensor(np.random.randn(examples, features), device=device)
linear = Linear(features,classes).to(device)
linear(X)

Tensor(
[[-0.81560801 -0.13384435]
 [-1.80962508 -1.7222418 ]
 [ 0.99101586 -0.16597353]
 [-0.96868566 -0.91026124]
 [-1.87804338 -0.42681709]
 [ 0.21561849 -0.31358686]
 [-2.2726735  -1.20302699]
 [ 0.22227201  0.21585687]
 [-1.6301671  -0.57861155]
 [ 1.14603732  1.21089466]], shape=(10, 2), device=gpu, requires_grad=True)

# Batch Norm

In [15]:
bn = BatchNorm1D(classes).to(device)
bn(linear(X))

Tensor(
[[-0.11463983  0.35330244]
 [-0.95487113 -1.73353113]
 [ 1.41247877  0.31109117]
 [-0.24403462 -0.6667526 ]
 [-1.01270435 -0.0316046 ]
 [ 0.7570442   0.11715706]
 [-1.34628069 -1.0513877 ]
 [ 0.76266834  0.81273924]
 [-0.80317735 -0.23103187]
 [ 1.54351665  2.120018  ]], shape=(10, 2), device=gpu, requires_grad=True)

# ReLU

In [16]:
relu = Relu()
relu(X)

Tensor(
[[0.82632699 0.         0.         0.         0.10415949]
 [0.         0.         0.         0.59571029 0.        ]
 [0.48896313 0.33070202 0.04166677 0.71322281 0.        ]
 [0.         0.         0.12824978 0.46738546 0.        ]
 [0.10152668 0.         0.         0.         0.97492475]
 [0.         0.         0.31972319 1.69710818 2.01429776]
 [0.         0.         0.         0.19353175 0.        ]
 [0.2697401  0.         0.83175818 0.         0.63164413]
 [0.92039927 0.         0.         0.         0.        ]
 [0.         0.03861814 1.70433041 0.         0.        ]], shape=(10, 5), device=gpu, requires_grad=False)

# Linear + ReLU + Batch Norm

In [17]:
relu(bn(linear(X)))

Tensor(
[[0.         0.35330244]
 [0.         0.        ]
 [1.41247877 0.31109117]
 [0.         0.        ]
 [0.         0.        ]
 [0.7570442  0.11715706]
 [0.         0.        ]
 [0.76266834 0.81273924]
 [0.         0.        ]
 [1.54351665 2.120018  ]], shape=(10, 2), device=gpu, requires_grad=True)