# Tensor
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/docs/learn/basics/01-tensor.ipynb)
[![Open in GitHub](https://img.shields.io/badge/Open%20in-GitHub-black?logo=github)](https://github.com/Mitchell-Mirano/sorix/blob/develop/docs/learn/basics/01-tensor.ipynb)
[![Open in Docs](https://img.shields.io/badge/Open%20in-Docs-blue?logo=readthedocs)](http://127.0.0.1:8000/sorix/learn/basics/01-tensor/)


The **Tensor** is Sorix's core data structure, analogous to **NumPy** arrays but with the added ability to record every operation within a [computational graph](../02-graph). This operation tracking is what enables the automatic computation of gradients[(Autograd)](../03-autograd).

In [1]:
# Uncomment the next line and run this cell to install sorix
#!pip install 'sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop'

In [2]:
import sorix
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Create a Tensor
A tensor can be initialized from a NumPy array, a pandas DataFrame, or a Python list. Internally, Sorix converts any supported input into a NumPy array.

In [3]:
# from list
a = sorix.tensor([1,2,3])
a

tensor([1, 2, 3])

In [4]:
#from numpy
a = sorix.tensor(np.random.rand(5,5),dtype=sorix.float32)
a

tensor([[0.8875218 , 0.8722612 , 0.45432606, 0.93933207, 0.52487546],
        [0.8130493 , 0.25705537, 0.07710341, 0.9770084 , 0.08418164],
        [0.5249847 , 0.2720534 , 0.47588047, 0.80568045, 0.7150026 ],
        [0.07884786, 0.7202018 , 0.6987711 , 0.39133266, 0.35854226],
        [0.02536704, 0.99360985, 0.83115023, 0.6919879 , 0.60279596]])

In [5]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

tensor([[0.464307, 0.278199, 0.793136, 0.618634, 0.729128],
        [0.182403, 0.187902, 0.957675, 0.784397, 0.467162],
        [0.664873, 0.887387, 0.035765, 0.841349, 0.687347],
        [0.906638, 0.473387, 0.639977, 0.352944, 0.432614],
        [0.725385, 0.90451 , 0.622032, 0.783273, 0.980809]], dtype=sorix.float64)

To access the underlying NumPy array within a Sorix tensor, you can use the `data` attribute and apply any NumPy operation directly to it.

In [6]:
t.data

array([[0.464307, 0.278199, 0.793136, 0.618634, 0.729128],
       [0.182403, 0.187902, 0.957675, 0.784397, 0.467162],
       [0.664873, 0.887387, 0.035765, 0.841349, 0.687347],
       [0.906638, 0.473387, 0.639977, 0.352944, 0.432614],
       [0.725385, 0.90451 , 0.622032, 0.783273, 0.980809]])

In [7]:
type(t.data)

numpy.ndarray

## Sorix utils to create tensors

In [8]:
t = sorix.as_tensor([1,2,3])
t

tensor([1, 2, 3])

In [9]:
t = sorix.randn(3,4)
t

tensor([[-0.1117351 ,  0.72765404,  0.63927042,  0.95709666],
        [ 1.20692758,  0.75952984, -2.00101265, -0.00603791],
        [ 0.85302397, -0.91623712,  1.04877897,  0.52891953]], dtype=sorix.float64)

In [10]:
t = sorix.zeros((3,4))
t

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=sorix.float64)

In [11]:
t = sorix.ones((3,4))
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=sorix.float64)

In [12]:
t = sorix.eye(3)
t

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=sorix.float64)

In [13]:
t = sorix.diag([1,2,3])
t

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [14]:
t = sorix.randint(0,10,(3,4))
t

tensor([[2, 0, 9, 1],
        [5, 9, 8, 9],
        [1, 4, 8, 7]])

In [15]:
t = sorix.arange(0,10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
t = sorix.linspace(0,10,5)
t

tensor([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=sorix.float64)

In [17]:
t = sorix.logspace(0,10,5)
t

tensor([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
        1.00000000e+10], dtype=sorix.float64)

In [18]:
t = sorix.randperm(5)
t

tensor([0, 2, 1, 3, 4])

## Basic Operations

In [19]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

tensor([1, 2, 3])
tensor([3, 4, 5])


In [20]:
c = a + b
c

tensor([4, 6, 8])

In [21]:
c = a - b
c

tensor([-2, -2, -2])

In [22]:
c = a * b
c

tensor([ 3,  8, 15])

In [23]:
c = a@b
c

tensor(26)

In [24]:
c = a**2
c

tensor([1, 4, 9])

## Slicing

In [25]:
a = sorix.tensor(np.random.rand(5,5))
a

tensor([[0.89074174, 0.82641051, 0.64003597, 0.63599003, 0.5430093 ],
        [0.14414357, 0.30624306, 0.3138804 , 0.21198534, 0.32460343],
        [0.05238621, 0.77985813, 0.94831727, 0.69182048, 0.08329619],
        [0.28750335, 0.21281202, 0.04782505, 0.65041847, 0.37878679],
        [0.92900392, 0.70028564, 0.85415062, 0.54456033, 0.88031825]], dtype=sorix.float64)

In [26]:
a[3,:]

tensor([0.28750335, 0.21281202, 0.04782505, 0.65041847, 0.37878679], dtype=sorix.float64)

In [27]:
a[3,3]

tensor(0.65041846)

In [28]:
a[:,3]

tensor([0.63599003, 0.21198534, 0.69182048, 0.65041847, 0.54456033], dtype=sorix.float64)

## Using GPU

When running on a GPU, Sorix uses **CuPy** arrays instead of NumPy. You can enable GPU execution by setting the `device` parameter to `'cuda'` (the default is `'cpu'`). When `'cuda'` is specified, Sorix creates CuPy-based tensors and executes all operations on the GPU.

To check whether a GPU is available, you can call `sorix.cuda.is_available()`. Refer to the examples below.


In [29]:
device = 'cuda' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'cuda'

In [30]:
a = sorix.tensor(np.random.rand(5,5), device=device)
b = sorix.tensor(np.random.rand(5,5), device=device)
c = a + b
c

tensor([[1.67394179, 0.76782471, 1.4553117 , 0.4982286 , 0.7237406 ],
        [0.43677627, 1.75496649, 0.25388764, 0.24171026, 1.33351447],
        [1.05401728, 1.28646555, 0.16121624, 0.51168813, 0.77921796],
        [0.39844802, 1.75928265, 0.8210317 , 0.85505205, 0.74328671],
        [1.13375151, 0.21292328, 0.97153513, 1.61702451, 1.33314178]], device='cuda:0', dtype=sorix.float64)