# Tensor
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/feature/docs_learn/docs/learn/basics/01-tensor.ipynb)
[![Open in GitHub](https://img.shields.io/badge/Open%20in-GitHub-black?logo=github)](https://github.com/Mitchell-Mirano/sorix/blob/feature/docs_learn/docs/learn/basics/01-tensor.ipynb)
[![Open in Docs](https://img.shields.io/badge/Open%20in-Docs-blue?logo=readthedocs)](http://127.0.0.1:8000/sorix/learn/basics/01-tensor/)


The **Tensor** is Sorix's core data structure, analogous to **NumPy** arrays but with the added ability to record every operation within a [computational graph](../02-graph). This operation tracking is what enables the automatic computation of gradients[(Autograd)](../03-autograd).

In [1]:
# Uncomment the next line and run this cell to install sorix
#!pip install 'sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@feature/docs_learn/docs_learn/docs_learn/docs_learn'

In [2]:
import sorix
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Create a Tensor
A tensor can be initialized from a NumPy array, a pandas DataFrame, or a Python list. Internally, Sorix converts any supported input into a NumPy array.

In [3]:
# from list
a = sorix.tensor([1,2,3])
a

tensor([1, 2, 3])

In [4]:
#from numpy
a = sorix.tensor(np.random.rand(5,5),dtype=sorix.float32)
a

tensor([[0.6804612 , 0.23954263, 0.04631325, 0.45137417, 0.40532094],
        [0.6169146 , 0.9748863 , 0.0304742 , 0.53584003, 0.945324  ],
        [0.28255406, 0.6641686 , 0.27768067, 0.6058376 , 0.744641  ],
        [0.0051461 , 0.2487435 , 0.19999287, 0.7273436 , 0.5725697 ],
        [0.27568677, 0.04579547, 0.7581017 , 0.8880476 , 0.02218847]])

In [5]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

tensor([[0.464307, 0.278199, 0.793136, 0.618634, 0.729128],
        [0.182403, 0.187902, 0.957675, 0.784397, 0.467162],
        [0.664873, 0.887387, 0.035765, 0.841349, 0.687347],
        [0.906638, 0.473387, 0.639977, 0.352944, 0.432614],
        [0.725385, 0.90451 , 0.622032, 0.783273, 0.980809]], dtype=sorix.float64)

To access the underlying NumPy array within a Sorix tensor, you can use the `data` attribute and apply any NumPy operation directly to it.

In [6]:
t.data

array([[0.464307, 0.278199, 0.793136, 0.618634, 0.729128],
       [0.182403, 0.187902, 0.957675, 0.784397, 0.467162],
       [0.664873, 0.887387, 0.035765, 0.841349, 0.687347],
       [0.906638, 0.473387, 0.639977, 0.352944, 0.432614],
       [0.725385, 0.90451 , 0.622032, 0.783273, 0.980809]])

In [7]:
type(t.data)

numpy.ndarray

## Sorix utils to create tensors

In [8]:
t = sorix.as_tensor([1,2,3])
t

tensor([1, 2, 3])

In [9]:
t = sorix.randn(3,4)
t

tensor([[-0.57018307, -0.94452469,  0.59222032, -0.54727245],
        [ 1.80325528,  0.3600453 ,  2.75890741,  0.16609284],
        [ 1.30125956,  0.3921614 ,  1.30620691,  1.12232971]], dtype=sorix.float64)

In [10]:
t = sorix.zeros((3,4))
t

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=sorix.float64)

In [11]:
t = sorix.ones((3,4))
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=sorix.float64)

In [12]:
t = sorix.eye(3)
t

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=sorix.float64)

In [13]:
t = sorix.diag([1,2,3])
t

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [14]:
t = sorix.randint(0,10,(3,4))
t

tensor([[8, 6, 4, 1],
        [7, 4, 2, 3],
        [9, 0, 2, 7]])

In [15]:
t = sorix.arange(0,10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
t = sorix.linspace(0,10,5)
t

tensor([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=sorix.float64)

In [17]:
t = sorix.logspace(0,10,5)
t

tensor([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
        1.00000000e+10], dtype=sorix.float64)

In [18]:
t = sorix.randperm(5)
t

tensor([3, 2, 1, 4, 0])

## Basic Operations

In [19]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

tensor([1, 2, 3])
tensor([3, 4, 5])


In [20]:
c = a + b
c

tensor([4, 6, 8])

In [21]:
c = a - b
c

tensor([-2, -2, -2])

In [22]:
c = a * b
c

tensor([ 3,  8, 15])

In [23]:
c = a@b
c

tensor(26)

In [24]:
c = a**2
c

tensor([1, 4, 9])

## Slicing

In [25]:
a = sorix.tensor(np.random.rand(5,5))
a

tensor([[0.26867713, 0.57266612, 0.3146687 , 0.14633559, 0.11369866],
        [0.53272895, 0.35194128, 0.37647936, 0.9327882 , 0.73812835],
        [0.70697115, 0.44447529, 0.39878382, 0.38391531, 0.59910094],
        [0.17398816, 0.52291319, 0.44279404, 0.45232494, 0.52277749],
        [0.55449761, 0.72156408, 0.00394382, 0.45557545, 0.92729364]], dtype=sorix.float64)

In [26]:
a[3,:]

tensor([0.17398816, 0.52291319, 0.44279404, 0.45232494, 0.52277749], dtype=sorix.float64)

In [27]:
a[3,3]

tensor(0.45232493)

In [28]:
a[:,3]

tensor([0.14633559, 0.9327882 , 0.38391531, 0.45232494, 0.45557545], dtype=sorix.float64)

## Using GPU

When running on a GPU, Sorix uses **CuPy** arrays instead of NumPy. You can enable GPU execution by setting the `device` parameter to `'cuda'` (the default is `'cpu'`). When `'cuda'` is specified, Sorix creates CuPy-based tensors and executes all operations on the GPU.

To check whether a GPU is available, you can call `sorix.cuda.is_available()`. Refer to the examples below.


In [29]:
device = 'cuda' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 14.0.1


'cuda'

In [30]:
a = sorix.tensor(np.random.rand(5,5), device=device)
b = sorix.tensor(np.random.rand(5,5), device=device)
c = a + b
c

tensor([[1.23187749, 1.43711433, 0.72693987, 1.15844634, 0.47046409],
        [1.28477485, 1.2041812 , 1.08623305, 0.33980393, 1.44577789],
        [1.03952929, 1.95658748, 1.42215147, 1.30195997, 0.9172764 ],
        [0.91563421, 1.73307578, 1.0237092 , 1.46267897, 1.00282323],
        [0.45580533, 1.57156608, 1.31385239, 1.19407027, 1.25425271]], device='cuda:0', dtype=sorix.float64)