# Tensor
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/sorix/blob/develop/docs/learn/basics/01-tensor.ipynb)
[![Open in GitHub](https://img.shields.io/badge/Open%20in-GitHub-black?logo=github)](https://github.com/Mitchell-Mirano/sorix/blob/develop/docs/learn/basics/01-tensor.ipynb)
[![Open in Docs](https://img.shields.io/badge/Open%20in-Docs-blue?logo=readthedocs)](http://127.0.0.1:8000/sorix/learn/basics/01-tensor/)


The **Tensor** is Sorix's core data structure, analogous to **NumPy** arrays but with the added ability to record every operation within a [computational graph](../02-graph). This operation tracking is what enables the automatic computation of gradients[(Autograd)](../03-autograd).

In [1]:
# Uncomment the next line and run this cell to install sorix
#!pip install 'sorix @ git+https://github.com/Mitchell-Mirano/sorix.git@develop'

In [2]:
import sorix
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Create a Tensor
A tensor can be initialized from a NumPy array, a pandas DataFrame, or a Python list. Internally, Sorix converts any supported input into a NumPy array.

In [3]:
# from list
a = sorix.tensor([1,2,3])
a

tensor([1, 2, 3])

In [4]:
#from numpy
a = sorix.tensor(np.random.rand(5,5),dtype=sorix.float32)
a

tensor([[0.4669392 , 0.25830635, 0.17271163, 0.34917644, 0.6971084 ],
        [0.07501335, 0.70437276, 0.8089504 , 0.32269633, 0.08195651],
        [0.24718356, 0.48148096, 0.2500892 , 0.6715827 , 0.4582112 ],
        [0.76806074, 0.6955186 , 0.25456154, 0.16475736, 0.835603  ],
        [0.7792379 , 0.4497958 , 0.43319383, 0.14997001, 0.9462468 ]])

In [5]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = sorix.tensor(data)
t

tensor([[0.464307, 0.278199, 0.793136, 0.618634, 0.729128],
        [0.182403, 0.187902, 0.957675, 0.784397, 0.467162],
        [0.664873, 0.887387, 0.035765, 0.841349, 0.687347],
        [0.906638, 0.473387, 0.639977, 0.352944, 0.432614],
        [0.725385, 0.90451 , 0.622032, 0.783273, 0.980809]], dtype=sorix.float64)

To access the underlying NumPy array within a Sorix tensor, you can use the `data` attribute and apply any NumPy operation directly to it.

In [6]:
t.data

array([[0.464307, 0.278199, 0.793136, 0.618634, 0.729128],
       [0.182403, 0.187902, 0.957675, 0.784397, 0.467162],
       [0.664873, 0.887387, 0.035765, 0.841349, 0.687347],
       [0.906638, 0.473387, 0.639977, 0.352944, 0.432614],
       [0.725385, 0.90451 , 0.622032, 0.783273, 0.980809]])

In [7]:
type(t.data)

numpy.ndarray

## Sorix utils to create tensors

In [8]:
t = sorix.as_tensor([1,2,3])
t

tensor([1, 2, 3])

In [9]:
t = sorix.randn(3,4)
t

tensor([[-0.56414366,  0.68387902,  2.30175619,  0.87618908],
        [ 0.68025521, -1.49775645,  0.2512605 , -0.0595177 ],
        [ 0.88005558, -0.26975998, -0.66301449,  1.47888161]], dtype=sorix.float64)

In [10]:
t = sorix.zeros((3,4))
t

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=sorix.float64)

In [11]:
t = sorix.ones((3,4))
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=sorix.float64)

In [12]:
t = sorix.eye(3)
t

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=sorix.float64)

In [13]:
t = sorix.diag([1,2,3])
t

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [14]:
t = sorix.randint(0,10,(3,4))
t

tensor([[8, 2, 0, 2],
        [6, 6, 3, 5],
        [2, 7, 8, 8]])

In [15]:
t = sorix.arange(0,10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
t = sorix.linspace(0,10,5)
t

tensor([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=sorix.float64)

In [17]:
t = sorix.logspace(0,10,5)
t

tensor([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
        1.00000000e+10], dtype=sorix.float64)

In [18]:
t = sorix.randperm(5)
t

tensor([3, 2, 4, 0, 1])

## Basic Operations

In [19]:
a = sorix.tensor([1,2,3])
b = sorix.tensor([3,4,5])

print(a)
print(b)

tensor([1, 2, 3])
tensor([3, 4, 5])


In [20]:
c = a + b
c

tensor([4, 6, 8])

In [21]:
c = a - b
c

tensor([-2, -2, -2])

In [22]:
c = a * b
c

tensor([ 3,  8, 15])

In [23]:
c = a@b
c

tensor(26)

In [24]:
c = a**2
c

tensor([1, 4, 9])

## Slicing

In [25]:
a = sorix.tensor(np.random.rand(5,5))
a

tensor([[0.33987798, 0.03811597, 0.39599076, 0.32222796, 0.00508232],
        [0.66589546, 0.63684787, 0.74262107, 0.51206985, 0.70650136],
        [0.92836039, 0.79982129, 0.25448658, 0.86827673, 0.18899537],
        [0.15006951, 0.29802253, 0.88025401, 0.32155012, 0.64457792],
        [0.92545462, 0.42437894, 0.79312816, 0.33993544, 0.58536344]], dtype=sorix.float64)

In [26]:
a[3,:]

tensor([0.15006951, 0.29802253, 0.88025401, 0.32155012, 0.64457792], dtype=sorix.float64)

In [27]:
a[3,3]

tensor(0.32155013)

In [28]:
a[:,3]

tensor([0.32222796, 0.51206985, 0.86827673, 0.32155012, 0.33993544], dtype=sorix.float64)

## Using GPU

When running on a GPU, Sorix uses **CuPy** arrays instead of NumPy. You can enable GPU execution by setting the `device` parameter to `'cuda'` (the default is `'cpu'`). When `'cuda'` is specified, Sorix creates CuPy-based tensors and executes all operations on the GPU.

To check whether a GPU is available, you can call `sorix.cuda.is_available()`. Refer to the examples below.


In [29]:
device = 'cuda' if sorix.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 14.0.1


'cuda'

In [30]:
a = sorix.tensor(np.random.rand(5,5), device=device)
b = sorix.tensor(np.random.rand(5,5), device=device)
c = a + b
c

tensor([[1.86317394, 1.05873891, 1.57308708, 1.3664417 , 0.40913254],
        [1.63317389, 1.22718501, 1.65357648, 1.13932971, 1.49489587],
        [1.83586158, 1.45774027, 0.11213706, 1.43864762, 0.47601946],
        [0.58940668, 0.89418561, 1.24149957, 0.94983426, 1.56736688],
        [1.21253088, 1.12984833, 0.22344371, 1.32425951, 1.12321841]], device='cuda:0', dtype=sorix.float64)